id = "fde76de2-1543-4eca-9d43-b40f24ec8241"
created_at = "2026-08-11T09:00:44.874752400+00:00"
title = "Make viewer frontend assets checkout-local"
state = "open"
component = "install-ctl"
parent_ticket_id = "3a624bf6-f240-4ea8-b0bb-1bceac883b6b"
priority = "high"
risk_level = "medium"
type = "task"
