id = "de697c71-9328-4133-8c77-d01e8b885940"
created_at = "2026-03-29T03:46:25.365416300Z"
component = "context-editor"
phase = "ui-framework"
priority = "medium"
state = "new"
title = "Impl: Open parameter manipulation UI for simulations and shaders"
type = "tracker-improvement"
