id = "4c58e8fb-73ad-4173-b5ee-3b87eafd3940"
created_at = "2026-03-29T06:14:16.862305300Z"
priority = "high"
state = "done"
title = "Feature: SVO LOD Management & GPU Streaming"
type = "tracker-improvement"
