id = "0c3f11d3-2475-470c-a191-beedd2c8e53c"
created_at = "2026-05-05T23:01:28.461970500+00:00"
title = "repo-qa"
state = "draft"
component = "repo-qa"
scope = "system"
slug = "repo-qa"
type = "specification"
