//! Log file parser for tracing JSON output.
//!
//! Parses pretty-printed JSON logs generated by `context-trace`'s
//! `PrettyJsonWriter`. Each JSON object may span multiple lines with
//! indentation. This is the canonical log parser — `viewer-api` and
//! `log-viewer` re-export from here.

use once_cell::sync::Lazy;
use regex::Regex;
use serde::{
    Deserialize,
    Serialize,
};
use std::collections::HashMap;

// Regex to strip ANSI escape codes
static ANSI_REGEX: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"\x1b\[[0-9;]*m").unwrap());

// Regex to parse panic location from message: "panicked at <file>:<line>:<col>:"
static PANIC_LOCATION_REGEX: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"panicked at ([^:]+):(\d+):(\d+):").unwrap());

// Regex to parse assertion diff header
static ASSERTION_DIFF_REGEX: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?s)assertion failed: `\(left == right\)`.*?Diff < (\w+) / (\w+) >\s*:\s*(.+)")
        .unwrap()
});

/// Strip ANSI escape codes from a string.
fn strip_ansi_codes(s: &str) -> String {
    ANSI_REGEX.replace_all(s, "").to_string()
}

/// Parse panic location from message like "panicked at file.rs:123:5: assertion..."
fn parse_panic_location(message: &str) -> Option<(String, u32, u32)> {
    PANIC_LOCATION_REGEX.captures(message).map(|caps| {
        let file = caps.get(1).unwrap().as_str().to_string();
        let line: u32 = caps.get(2).unwrap().as_str().parse().unwrap_or(0);
        let col: u32 = caps.get(3).unwrap().as_str().parse().unwrap_or(0);
        (file, line, col)
    })
}

/// Parsed assertion diff data.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "ts-gen", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-gen",
    ts(
        export,
        export_to = "../../../packages/context-types/src/generated/"
    )
)]
pub struct AssertionDiff {
    pub title: String,
    pub left_label: String,
    pub right_label: String,
    pub left_value: String,
    pub right_value: String,
}

/// Parse assertion diff from message.
fn parse_assertion_diff(message: &str) -> Option<AssertionDiff> {
    let captures = ASSERTION_DIFF_REGEX.captures(message)?;
    let left_label = captures.get(1)?.as_str().to_string();
    let right_label = captures.get(2)?.as_str().to_string();
    let diff_content = captures.get(3)?.as_str();

    let mut left_lines = Vec::new();
    let mut right_lines = Vec::new();

    for line in diff_content.lines() {
        if let Some(rest) = line.strip_prefix('<') {
            left_lines.push(rest.to_string());
        } else if let Some(rest) = line.strip_prefix('>') {
            right_lines.push(rest.to_string());
        }
    }

    Some(AssertionDiff {
        title: "assertion failed: `(left == right)`".to_string(),
        left_label,
        right_label,
        left_value: left_lines.join("\n"),
        right_value: right_lines.join("\n"),
    })
}

/// A parsed log entry — the full representation with all fields.
///
/// This is the canonical log entry type. The `LogEntryInfo` type in
/// `crate::types` is a simplified view for API responses.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "ts-gen", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-gen",
    ts(
        export,
        export_to = "../../../packages/context-types/src/generated/"
    )
)]
pub struct LogEntry {
    /// Entry index (1-based).
    pub line_number: usize,
    /// Log level (TRACE, DEBUG, INFO, WARN, ERROR).
    pub level: String,
    /// Timestamp string.
    pub timestamp: Option<String>,
    /// The log message.
    pub message: String,
    /// Event type (event, span_enter, span_exit, span_new, span_close).
    pub event_type: String,
    /// Span name (if this is a span event).
    pub span_name: Option<String>,
    /// Indentation depth (number of parent spans).
    pub depth: usize,
    /// Additional fields (preserves structured JSON values).
    #[schemars(with = "std::collections::HashMap<String, serde_json::Value>")]
    #[cfg_attr(feature = "ts-gen", ts(type = "Record<string, unknown>"))]
    pub fields: HashMap<String, serde_json::Value>,
    /// Source file location (from tracing macro).
    pub file: Option<String>,
    /// Source line number (from tracing macro).
    pub source_line: Option<u32>,
    /// Panic file location (from panic info, points to actual assertion).
    pub panic_file: Option<String>,
    /// Panic line number.
    pub panic_line: Option<u32>,
    /// Parsed assertion diff (for failed assertions).
    pub assertion_diff: Option<AssertionDiff>,
    /// Stack trace (for panics).
    pub backtrace: Option<String>,
    /// Raw summary string.
    pub raw: String,
}

/// Conversion from full `LogEntry` to the simplified `LogEntryInfo` API type.
impl From<&LogEntry> for crate::types::LogEntryInfo {
    fn from(entry: &LogEntry) -> Self {
        Self {
            entry_number: entry.line_number,
            level: entry.level.clone(),
            timestamp: entry.timestamp.clone(),
            message: entry.message.clone(),
            event_type: entry.event_type.clone(),
            span_name: entry.span_name.clone(),
            depth: entry.depth,
            fields: serde_json::to_value(&entry.fields).unwrap_or_default(),
            source_file: entry.file.clone(),
            source_line: entry.source_line,
        }
    }
}

/// Raw JSON structure from tracing-subscriber.
#[derive(Debug, Deserialize)]
struct TracingJson {
    timestamp: Option<String>,
    level: Option<String>,
    fields: Option<serde_json::Value>,
    target: Option<String>,
    span: Option<SpanEntry>,
    spans: Option<Vec<SpanEntry>>,
    #[serde(rename = "filename")]
    file: Option<String>,
    #[serde(rename = "line_number")]
    line: Option<u32>,
}

#[derive(Debug, Deserialize)]
struct SpanInfo {
    name: Option<String>,
    #[serde(flatten)]
    fields: HashMap<String, serde_json::Value>,
}

/// Wrapper that deserializes from either a string or a SpanInfo object.
#[derive(Debug)]
struct SpanEntry(SpanInfo);

impl<'de> serde::Deserialize<'de> for SpanEntry {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = serde_json::Value::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(name) => Ok(SpanEntry(SpanInfo {
                name: Some(name),
                fields: HashMap::new(),
            })),
            serde_json::Value::Object(_) => {
                let info: SpanInfo =
                    serde_json::from_value(serde_json::Value::Object(
                        value.as_object().cloned().unwrap_or_default(),
                    ))
                    .map_err(serde::de::Error::custom)?;
                Ok(SpanEntry(info))
            },
            _ =>
                Err(serde::de::Error::custom("span must be a string or object")),
        }
    }
}

/// Parser for log files produced by `context-trace`'s `PrettyJsonWriter`.
pub struct LogParser;

impl LogParser {
    pub fn new() -> Self {
        Self
    }

    /// Parse log content into structured entries.
    ///
    /// Handles both pretty-printed JSON (multi-line) and NDJSON formats.
    /// Uses serde_json's streaming deserializer to parse consecutive JSON objects.
    pub fn parse(
        &self,
        content: &str,
    ) -> Vec<LogEntry> {
        let mut entries = Vec::new();

        let stream = serde_json::Deserializer::from_str(content)
            .into_iter::<TracingJson>();

        for (index, result) in stream.enumerate() {
            let entry_num = index + 1;

            match result {
                Ok(json) => {
                    entries.push(self.json_to_entry(entry_num, &json));
                },
                Err(e) => {
                    entries.push(LogEntry {
                        line_number: entry_num,
                        level: "ERROR".to_string(),
                        timestamp: None,
                        message: format!("JSON parse error: {}", e),
                        event_type: "error".to_string(),
                        span_name: None,
                        depth: 0,
                        fields: HashMap::new(),
                        file: None,
                        source_line: None,
                        panic_file: None,
                        panic_line: None,
                        assertion_diff: None,
                        backtrace: None,
                        raw: format!("Parse error at entry {}", entry_num),
                    });
                    // Stop on parse errors to avoid cascading failures
                    break;
                },
            }
        }

        entries
    }

    fn json_to_entry(
        &self,
        line_number: usize,
        json: &TracingJson,
    ) -> LogEntry {
        let level = json.level.clone().unwrap_or_else(|| "INFO".to_string());

        let (message, event_type, backtrace) =
            self.extract_message_and_type(json);

        let span_name = json
            .span
            .as_ref()
            .and_then(|s| s.0.name.clone())
            .or_else(|| {
                json.spans
                    .as_ref()
                    .and_then(|spans| spans.last())
                    .and_then(|s| s.0.name.clone())
            });

        let depth = json.spans.as_ref().map(|s| s.len()).unwrap_or(0);

        let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
        if let Some(field_value) = &json.fields {
            if let Some(obj) = field_value.as_object() {
                for (key, value) in obj {
                    if key != "message"
                        && key != "backtrace"
                        && key != "panic_file"
                        && key != "panic_line"
                        && key != "panic_column"
                    {
                        fields.insert(key.clone(), value.clone());
                    }
                }
            }
        }

        if let Some(span) = &json.span {
            for (key, value) in &span.0.fields {
                if key != "name" {
                    fields.insert(key.clone(), value.clone());
                }
            }
        }

        let file = json.file.clone();
        let source_line = json.line;

        let mut panic_file = None;
        let mut panic_line = None;

        // First check for panic location fields (from panic hook)
        if let Some(field_value) = &json.fields {
            if let Some(obj) = field_value.as_object() {
                if let Some(pf) = obj.get("panic_file") {
                    if let Some(s) = pf.as_str() {
                        panic_file = Some(s.to_string());
                    }
                }
                if let Some(pl) = obj.get("panic_line") {
                    if let Some(n) = pl.as_u64() {
                        panic_line = Some(n as u32);
                    }
                }
            }
        }

        // If no panic fields, try to parse from message (for old log files)
        if panic_file.is_none() && message.contains("panicked at") {
            if let Some((pf, pl, _col)) = parse_panic_location(&message) {
                panic_file = Some(pf);
                panic_line = Some(pl);
            }
        }

        let assertion_diff = parse_assertion_diff(&message);

        LogEntry {
            line_number,
            level: level.clone(),
            timestamp: json.timestamp.clone(),
            message: message.clone(),
            event_type,
            span_name,
            depth,
            fields,
            file,
            source_line,
            panic_file,
            panic_line,
            assertion_diff,
            backtrace,
            raw: format!("[{}] {}", level, message),
        }
    }

    fn extract_message_and_type(
        &self,
        json: &TracingJson,
    ) -> (String, String, Option<String>) {
        let mut message = String::new();
        let mut event_type = "event".to_string();
        let mut backtrace = None;

        if let Some(fields) = &json.fields {
            if let Some(obj) = fields.as_object() {
                if let Some(msg) = obj.get("message") {
                    message = match msg {
                        serde_json::Value::String(s) => strip_ansi_codes(s),
                        other => strip_ansi_codes(&other.to_string()),
                    };
                }

                if let Some(bt) = obj.get("backtrace") {
                    backtrace = match bt {
                        serde_json::Value::String(s) => Some(s.clone()),
                        other => Some(other.to_string()),
                    };
                }
            }
        }

        // Detect span events from message content
        if message.contains("new") || message.contains("enter") {
            if let Some(span) = &json.span {
                if span.0.name.is_some() {
                    if message.contains("new") {
                        event_type = "span_new".to_string();
                    } else {
                        event_type = "span_enter".to_string();
                    }
                }
            }
        } else if message.contains("close") || message.contains("exit") {
            if json.span.is_some() {
                event_type = "span_exit".to_string();
            }
        }

        // If message is empty, use target or generate a description
        if message.is_empty() {
            if let Some(span) = &json.span {
                if let Some(name) = &span.0.name {
                    message = format!("Span: {}", name);
                    event_type = "span_enter".to_string();
                }
            }
            if message.is_empty() {
                message = json
                    .target
                    .clone()
                    .unwrap_or_else(|| "Unknown".to_string());
            }
        }

        (message, event_type, backtrace)
    }
}

impl Default for LogParser {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_event() {
        let json = r#"{
            "timestamp": "2026-03-14T00:55:30.028572Z",
            "level": "INFO",
            "fields": {
                "message": "test message",
                "some_field": "value"
            },
            "target": "test_target",
            "filename": "test.rs",
            "line_number": 42
        }"#;

        let parser = LogParser::new();
        let entries = parser.parse(json);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].level, "INFO");
        assert_eq!(entries[0].message, "test message");
        assert_eq!(entries[0].file.as_deref(), Some("test.rs"));
        assert_eq!(entries[0].source_line, Some(42));
        assert!(entries[0].fields.contains_key("some_field"));
    }

    #[test]
    fn test_parse_multiple_entries() {
        let json = r#"{"timestamp": "t1", "level": "INFO", "fields": {"message": "first"}}
{"timestamp": "t2", "level": "WARN", "fields": {"message": "second"}}"#;

        let parser = LogParser::new();
        let entries = parser.parse(json);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].message, "first");
        assert_eq!(entries[1].message, "second");
        assert_eq!(entries[1].level, "WARN");
    }

    #[test]
    fn test_parse_span_enter() {
        let parser = LogParser::new();
        let content = r#"{"timestamp":"2024-01-01T00:00:00.000000Z","level":"INFO","fields":{"message":"enter"},"target":"test","span":{"name":"my_function"}}"#;
        let entries = parser.parse(content);

        assert_eq!(entries.len(), 1);
        let entry = &entries[0];
        assert_eq!(entry.level, "INFO");
        assert_eq!(entry.event_type, "span_enter");
        assert_eq!(entry.span_name.as_deref(), Some("my_function"));
    }

    #[test]
    fn test_parse_span_close() {
        let parser = LogParser::new();
        let content = r#"{"timestamp":"2024-01-01T00:00:00.000000Z","level":"INFO","fields":{"message":"close"},"target":"test","span":{"name":"my_function"}}"#;
        let entries = parser.parse(content);

        assert_eq!(entries.len(), 1);
        let entry = &entries[0];
        assert_eq!(entry.level, "INFO");
        assert_eq!(entry.event_type, "span_exit");
        assert_eq!(entry.span_name.as_deref(), Some("my_function"));
    }

    #[test]
    fn test_calculate_depth() {
        let parser = LogParser::new();
        let entry1 =
            r#"{"level":"INFO","fields":{"message":"test"},"spans":[]}"#;
        let entry2 = r#"{"level":"INFO","fields":{"message":"test"},"spans":[{"name":"a"}]}"#;
        let entry3 = r#"{"level":"INFO","fields":{"message":"test"},"spans":[{"name":"a"},{"name":"b"}]}"#;

        let entries =
            parser.parse(&format!("{}\n{}\n{}", entry1, entry2, entry3));
        assert_eq!(entries[0].depth, 0);
        assert_eq!(entries[1].depth, 1);
        assert_eq!(entries[2].depth, 2);
    }

    #[test]
    fn test_strip_ansi_codes() {
        assert_eq!(strip_ansi_codes("\x1b[31mred\x1b[0m"), "red");
        assert_eq!(strip_ansi_codes("no codes"), "no codes");
    }

    #[test]
    fn test_parse_panic_location() {
        let msg = "panicked at src/main.rs:42:5: assertion failed";
        let result = parse_panic_location(msg);
        assert!(result.is_some());
        let (file, line, col) = result.unwrap();
        assert_eq!(file, "src/main.rs");
        assert_eq!(line, 42);
        assert_eq!(col, 5);
    }

    #[test]
    fn test_default_impl() {
        let parser = LogParser::default();
        let entries =
            parser.parse(r#"{"level":"DEBUG","fields":{"message":"hi"}}"#);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].message, "hi");
    }
}
