id = "96dc0068-d05d-4e61-b785-144272119fa9"
created_at = "2026-06-02T23:12:13.690659600+00:00"
title = "workflow guidance generation and session capture scaffolding"
state = "draft"
component = "context-engine"
parent = "a4f48d84-50ed-4769-a42f-38321ea9600c"
scope = "internal"
slug = "context-engine/workflow-guidance-generation-and-session-capture"
type = "specification"
