id = "edc9aba9-11be-42f2-bdd7-35e3c5a2ce23"
created_at = "2026-06-14T13:46:48.344672300+00:00"
title = "[ticket-vscode] Fix canonical workspace selection when server exposes path-based or shared workspace ids"
state = "in-implementation"
deleted = true
effort = "1200"
type = "bug"
