id = "37dc83ab-af5c-4746-9c02-b27ffb8215a9"
created_at = "2026-06-15T00:10:06.951244300+00:00"
title = "[bug] Tantivy 0.22.1 fastfield panic breaks spec/store full-text search"
state = "new"
type = "tracker-improvement"
