id = "c5115990-529c-47ad-91bf-4dd1f8602d44"
created_at = "2026-03-29T05:39:46.075051500Z"
priority = "high"
state = "done"
title = "Voxel Inventory: Mini-SVO Items, Glass UI Rendering & Drag-to-World"
type = "tracker-improvement"
