id = "02c6700d-6ab2-44a8-aa69-4052ad2f76bb"
created_at = "2026-08-26T01:29:22.225995100+00:00"
title = "Consolidated workflow-tools entity stores"
state = "draft"
component = "workflow-tools"
scope = "public"
slug = "workflow-tools/entity-store-namespace"
type = "specification"
