id = "f52cc8e5-9faf-4a41-9c5b-ad7c2a381dd9"
created_at = "2026-08-06T19:59:30.559784300+00:00"
title = "[tooling] Define executable and hook registry schema with Markdown catalog generation"
state = "in-implementation"
component = "tooling"
effort = "3k"
parts = [{ id = "7fdc295c-4bd1-448c-8cc5-b3bc062562d7", kind = "requirements", path = "parts/7fdc295c-4bd1-448c-8cc5-b3bc062562d7.md", frozen = false, created_at = "2026-08-06T19:59:41.999343Z" }]
priority = "high"
related_specs = "97322185-2bda-4f25-85f7-f975a0b3fbad"
type = "task"
