id = "194ade77-6922-4be8-8c5b-4423173abcf6"
created_at = "2026-03-29T05:11:44.173672100Z"
priority = "high"
state = "done"
title = "[context-editor] Tiled Forward+ Rasterizer (Tile Binning + Fragment Compositing)"
type = "tracker-improvement"
