id = "3fec54f1-9c8f-4059-a366-7da6e9a1a645"
created_at = "2026-03-29T06:14:05.260243800+00:00"
title = "Force Compute Shader & SVO Collision"
state = "done"
priority = "high"
type = "tracker-improvement"
