id = "182940eb-0df3-4fa0-8aff-2abce6095708"
created_at = "2026-08-14T12:34:00.804576400+00:00"
title = "Repository architecture and dependency policies"
state = "draft"
component = "repo-guidance"
related_tickets = [{ ticket_id = "9a1bffce-b825-4f58-a078-2351d9bdaa16", workspace = "default", store_root = ".ticket" }, { ticket_id = "d2bf768f-4011-42fa-9149-97d6adb0c322", workspace = "default", store_root = ".ticket" }, { ticket_id = "665a5df8-eed9-4adb-8022-fe7f07955062", workspace = "default", store_root = ".ticket" }, { ticket_id = "a74f09cf-2c4b-4c13-9247-cd74519b6b7e", workspace = "default", store_root = ".ticket" }, { ticket_id = "69eb4118-19ec-4b5b-bb12-30e314029cc5", workspace = "default", store_root = ".ticket" }]
scope = "internal"
slug = "repo-guidance/repository-architecture-dependency-policies"
status = "active"
type = "specification"
