#![allow(unused)]
use crate::{
    graph::vertex::{
        child::Child,
        location::child::ChildLocation,
        pattern::pattern_width,
    },
    path::{
        RolePathUtils,
        accessors::{
            child::root::GraphRootChild,
            role::End,
        },
        mutators::move_path::key::TokenPosition,
    },
    tests::mock,
    trace::cache::key::{
        directed::{
            DirectedKey,
            up::UpKey,
        },
        props::{
            CursorPosition,
            RootKey,
            TargetKey,
        },
    },
};
use std::{
    borrow::Borrow,
    num::NonZeroUsize,
};
