id = "47f2a664-7803-4074-b40c-f41d3caf0c54"
created_at = "2026-07-25T13:55:30.305176700+00:00"
title = "[workflow-tools][artifacts] Migrate tool-scoped artifacts into their owning tool repositories"
state = "open"
component = "workflow-tools"
depends_on = ["47a0bcc3-f42d-475e-b05a-777293c4698e"]
effort = "1800"
priority = "high"
risk_level = "high"
type = "task"
