id = "b71658f1-8de2-444a-9be1-64b1d8ecce70"
created_at = "2026-07-26T18:20:27.673802900+00:00"
title = "Iteration Loop Workflow"
state = "draft"
component = "agent-tooling"
slug = "agent-workflow/iteration-loop"
type = "specification"
