id = "6283bde2-a4ad-45f7-ae26-15697bf5c410"
created_at = "2026-08-25T01:16:13.301964500+00:00"
title = "[workflow-tools] Prove minimal external consumer installation tutorial"
state = "open"
related_specs = "bc639ab3-8eda-4268-a7a2-34289bfeba4d"
type = "task"
