id = "4f284d45-e520-4d22-945e-f54bdd3c0175"
created_at = "2026-07-25T13:54:30.581591400+00:00"
title = "[workflow-tools][provisioning] Create GitHub repositories for extracted workflow tooling (user action)"
state = "done"
component = "workflow-tools"
effort = "200"
priority = "high"
risk_level = "low"
type = "task"
