id = "c522633d-7ec8-462a-ae00-30370e37a2d7"
created_at = "2026-08-22T22:24:15.479177200+00:00"
title = "Production Workflow: Tickets"
state = "draft"
component = "agent-workflow"
parent = "90e4fb79-2c60-42a6-ab10-91d243693150"
scope = "internal"
slug = "agent-workflow/production-cycle/tickets"
type = "specification"
