id = "c2409055-c489-441b-9a60-f3b3aa608522"
created_at = "2026-06-07T17:54:44.184619200+00:00"
title = "[memory-index] Memory workspace DAG indexing"
state = "new"
component = "context-engine"
depends_on = ["0dba399a-4691-4173-b921-17e5e6f6ebb8"]
priority = "medium"
type = "tracker-improvement"
