id = "18b6a9c5-7d9c-483c-a228-113903ed495f"
created_at = "2026-06-07T16:58:50.830822800+00:00"
title = "Generated context index hierarchy and semantic reference format"
state = "draft"
component = "context-engine"
scope = "internal"
slug = "generated-context/index-hierarchy-semantic-refs"
type = "specification"
