id = "61ce77f9-b6be-4667-9727-ffbd6bf6b8f4"
created_at = "2026-07-25T18:50:57.187723900+00:00"
title = "[workflow-tools][extraction] Extract ticket as first per-tool {domain} crate (pilot)"
state = "new"
component = "workflow-tools"
depends_on = ["1c452ff1-6edc-47c8-a73d-d07ce9b4d473"]
effort = "800"
priority = "high"
risk_level = "medium"
type = "task"
