/**
 * Cross-language tests for search path reconstruction.
 *
 * Test fixtures are generated by the Rust test
 * `context-trace::graph::search_path::tests::generate_cross_language_fixtures`.
 *
 * Run `cargo test -p context-trace generate_cross_language_fixtures` to
 * regenerate whenever search_path.rs types change.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';

import type { PathTransition, SnapshotEdge, VizPathGraph } from '../types/generated';
import { fromTransitions } from './reconstruction';
import { buildChildMap, findDescendantPath, edgePairKey } from './edge-highlighting';

interface TestFixture {
  name: string;
  transitions: PathTransition[];
  expected: VizPathGraph;
}

// Load fixtures generated by Rust
const fixturesPath = resolve(__dirname, 'test-fixtures.json');
const fixtures: TestFixture[] = JSON.parse(
  readFileSync(fixturesPath, 'utf-8'),
);

describe('search path reconstruction (cross-language)', () => {
  it('should have loaded at least one fixture', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  for (const fixture of fixtures) {
    it(`reconstructs "${fixture.name}" identically to Rust`, () => {
      const result = fromTransitions(fixture.transitions);
      expect(result).toEqual(fixture.expected);
    });
  }
});

describe('search path reconstruction edge cases', () => {
  it('empty transitions produce empty graph', () => {
    const result = fromTransitions([]);
    expect(result.start_node).toBeNull();
    expect(result.root).toBeNull();
    expect(result.done).toBe(false);
  });

  it('throws on PushParent before SetStartNode', () => {
    expect(() =>
      fromTransitions([
        {
          kind: 'push_parent',
          parent: { index: 1, width: 1 },
          edge: { from: 0, to: 1, pattern_idx: 0, sub_index: 0 },
        },
      ]),
    ).toThrow(/SetStartNode/);
  });

  it('throws on SetStartNode called twice', () => {
    expect(() =>
      fromTransitions([
        { kind: 'set_start_node', node: { index: 1, width: 1 } },
        { kind: 'set_start_node', node: { index: 2, width: 1 } },
      ]),
    ).toThrow(/twice/);
  });

  it('throws on PushChild before SetRoot', () => {
    expect(() =>
      fromTransitions([
        { kind: 'set_start_node', node: { index: 1, width: 1 } },
        {
          kind: 'push_child',
          child: { index: 3, width: 1 },
          edge: { from: 1, to: 3, pattern_idx: 0, sub_index: 0 },
        },
      ]),
    ).toThrow(/SetRoot/);
  });

  it('throws on PopChild on empty end_path', () => {
    expect(() =>
      fromTransitions([
        { kind: 'set_start_node', node: { index: 1, width: 1 } },
        {
          kind: 'set_root',
          root: { index: 10, width: 2 },
          edge: { from: 1, to: 10, pattern_idx: 0, sub_index: 0 },
        },
        { kind: 'pop_child' },
      ]),
    ).toThrow(/empty/);
  });

  it('throws on ReplaceChild on empty end_path', () => {
    expect(() =>
      fromTransitions([
        { kind: 'set_start_node', node: { index: 1, width: 1 } },
        {
          kind: 'set_root',
          root: { index: 10, width: 2 },
          edge: { from: 1, to: 10, pattern_idx: 0, sub_index: 0 },
        },
        {
          kind: 'replace_child',
          child: { index: 5, width: 1 },
          edge: { from: 10, to: 5, pattern_idx: 0, sub_index: 1 },
        },
      ]),
    ).toThrow(/empty/);
  });
});

// ---------------------------------------------------------------------------
// Edge highlighting utilities (Phase 5)
// ---------------------------------------------------------------------------

describe('buildChildMap', () => {
  it('builds adjacency from snapshot edges', () => {
    const edges: SnapshotEdge[] = [
      { from: 10, to: 7, pattern_idx: 0, sub_index: 0 },
      { from: 7, to: 5, pattern_idx: 0, sub_index: 0 },
      { from: 5, to: 3, pattern_idx: 0, sub_index: 0 },
    ];
    const map = buildChildMap(edges);
    expect(map.get(10)).toEqual([7]);
    expect(map.get(7)).toEqual([5]);
    expect(map.get(5)).toEqual([3]);
    expect(map.get(3)).toBeUndefined();
  });

  it('deduplicates multi-pattern edges to same child', () => {
    const edges: SnapshotEdge[] = [
      { from: 10, to: 7, pattern_idx: 0, sub_index: 0 },
      { from: 10, to: 7, pattern_idx: 1, sub_index: 0 },
      { from: 10, to: 5, pattern_idx: 0, sub_index: 1 },
    ];
    const map = buildChildMap(edges);
    // 7 appears once despite two edges, plus 5
    expect(map.get(10)!.sort()).toEqual([5, 7]);
  });
});

describe('findDescendantPath', () => {
  const linearEdges: SnapshotEdge[] = [
    { from: 10, to: 8, pattern_idx: 0, sub_index: 0 },
    { from: 8, to: 5, pattern_idx: 0, sub_index: 0 },
    { from: 5, to: 3, pattern_idx: 0, sub_index: 0 },
  ];
  const linearMap = buildChildMap(linearEdges);

  it('finds direct parent→child path', () => {
    expect(findDescendantPath(10, 8, linearMap)).toEqual([10, 8]);
  });

  it('finds multi-hop path through intermediates', () => {
    expect(findDescendantPath(10, 3, linearMap)).toEqual([10, 8, 5, 3]);
  });

  it('returns [node] for ancestor === descendant', () => {
    expect(findDescendantPath(5, 5, linearMap)).toEqual([5]);
  });

  it('returns null for unreachable target', () => {
    expect(findDescendantPath(3, 10, linearMap)).toBeNull();
  });

  it('returns null for disconnected node', () => {
    expect(findDescendantPath(10, 99, linearMap)).toBeNull();
  });

  it('handles branching topology', () => {
    const branchEdges: SnapshotEdge[] = [
      { from: 10, to: 7, pattern_idx: 0, sub_index: 0 },
      { from: 10, to: 6, pattern_idx: 0, sub_index: 1 },
      { from: 7, to: 3, pattern_idx: 0, sub_index: 0 },
      { from: 6, to: 4, pattern_idx: 0, sub_index: 0 },
    ];
    const branchMap = buildChildMap(branchEdges);
    // Path to one branch
    expect(findDescendantPath(10, 3, branchMap)).toEqual([10, 7, 3]);
    // Path to other branch
    expect(findDescendantPath(10, 4, branchMap)).toEqual([10, 6, 4]);
    // Cross-branch should fail
    expect(findDescendantPath(7, 4, branchMap)).toBeNull();
  });
});

describe('edge highlighting edge key computation', () => {
  // Helper: compute edge keys from a VizPathGraph + snapshot edges
  // using the same logic as useVisualizationState
  function computeEdgeKeys(sp: VizPathGraph, snapshotEdges: SnapshotEdge[]) {
    const childMap = buildChildMap(snapshotEdges);
    const startKeys = new Set<number>();
    const rootKeys = new Set<number>();
    const endKeys = new Set<number>();

    // Start path edges
    const startChain: number[] = [];
    if (sp.start_node) startChain.push(sp.start_node.index);
    for (const n of sp.start_path) startChain.push(n.index);

    for (let i = 0; i < startChain.length - 1; i++) {
      const path = findDescendantPath(startChain[i + 1]!, startChain[i]!, childMap);
      if (path) {
        for (let j = 0; j < path.length - 1; j++) {
          startKeys.add(edgePairKey(path[j]!, path[j + 1]!));
        }
      } else if (i < sp.start_edges.length) {
        const e = sp.start_edges[i]!;
        startKeys.add(edgePairKey(e.to, e.from));
      }
    }

    // Root edge(s)
    if (sp.root_edge && sp.root) {
      const startTop = sp.start_path.length > 0
        ? sp.start_path[sp.start_path.length - 1]!.index
        : sp.start_node?.index ?? -1;
      if (startTop >= 0) {
        const path = findDescendantPath(sp.root.index, startTop, childMap);
        if (path && path.length >= 2) {
          for (let j = 0; j < path.length - 1; j++) {
            rootKeys.add(edgePairKey(path[j]!, path[j + 1]!));
          }
        } else {
          rootKeys.add(edgePairKey(sp.root_edge.to, sp.root_edge.from));
        }
      }
    }

    // End path edges
    if (sp.root && sp.end_path.length > 0) {
      const target = sp.end_path[sp.end_path.length - 1]!.index;
      if (target !== sp.root.index) {
        const path = findDescendantPath(sp.root.index, target, childMap);
        if (path) {
          for (let j = 0; j < path.length - 1; j++) {
            endKeys.add(edgePairKey(path[j]!, path[j + 1]!));
          }
        } else {
          for (const e of sp.end_edges) {
            endKeys.add(edgePairKey(e.from, e.to));
          }
        }
      }
    }

    return { startKeys, rootKeys, endKeys };
  }

  it('highlights all intermediate edges on root edge path', () => {
    // Graph: root(10) → X(8) → startTop(7) → startNode(3)
    const edges: SnapshotEdge[] = [
      { from: 10, to: 8, pattern_idx: 0, sub_index: 0 },
      { from: 8, to: 7, pattern_idx: 0, sub_index: 0 },
      { from: 7, to: 3, pattern_idx: 0, sub_index: 0 },
    ];
    const sp: VizPathGraph = {
      start_node: { index: 3, width: 1 },
      start_path: [{ index: 7, width: 1 }],
      start_edges: [{ from: 3, to: 7, pattern_idx: 0, sub_index: 0 }],
      root: { index: 10, width: 2 },
      root_edge: { from: 7, to: 10, pattern_idx: 0, sub_index: 0 },
      end_path: [],
      end_edges: [],
      cursor_pos: 0,
      done: false,
      success: false,
    };
    const { startKeys, rootKeys } = computeEdgeKeys(sp, edges);

    // Start path: 7→3
    expect(startKeys.has(edgePairKey(7, 3))).toBe(true);
    expect(startKeys.size).toBe(1);

    // Root edge: should include BOTH 10→8 and 8→7
    expect(rootKeys.has(edgePairKey(10, 8))).toBe(true);
    expect(rootKeys.has(edgePairKey(8, 7))).toBe(true);
    expect(rootKeys.size).toBe(2);
  });

  it('highlights direct root edge when no intermediates', () => {
    // Graph: root(10) → startNode(3)
    const edges: SnapshotEdge[] = [
      { from: 10, to: 3, pattern_idx: 0, sub_index: 0 },
    ];
    const sp: VizPathGraph = {
      start_node: { index: 3, width: 1 },
      start_path: [],
      start_edges: [],
      root: { index: 10, width: 2 },
      root_edge: { from: 3, to: 10, pattern_idx: 0, sub_index: 0 },
      end_path: [],
      end_edges: [],
      cursor_pos: 0,
      done: false,
      success: false,
    };
    const { rootKeys } = computeEdgeKeys(sp, edges);
    expect(rootKeys.has(edgePairKey(10, 3))).toBe(true);
    expect(rootKeys.size).toBe(1);
  });

  it('fills in intermediate end-path edges via BFS', () => {
    // Graph: root(10) → X(8) → child(5)
    const edges: SnapshotEdge[] = [
      { from: 10, to: 8, pattern_idx: 0, sub_index: 0 },
      { from: 8, to: 5, pattern_idx: 0, sub_index: 0 },
    ];
    const sp: VizPathGraph = {
      start_node: { index: 3, width: 1 },
      start_path: [],
      start_edges: [],
      root: { index: 10, width: 2 },
      root_edge: { from: 3, to: 10, pattern_idx: 0, sub_index: 0 },
      end_path: [{ index: 5, width: 1 }],
      end_edges: [{ from: 10, to: 5, pattern_idx: 0, sub_index: 0 }],
      cursor_pos: 0,
      done: false,
      success: false,
    };
    const { endKeys } = computeEdgeKeys(sp, edges);
    // Should find 10→8 and 8→5 via BFS
    expect(endKeys.has(edgePairKey(10, 8))).toBe(true);
    expect(endKeys.has(edgePairKey(8, 5))).toBe(true);
    expect(endKeys.size).toBe(2);
  });

  it('falls back to direct edges when BFS cannot reach target', () => {
    // Graph has no path from root to child (disconnected)
    const edges: SnapshotEdge[] = [
      { from: 10, to: 7, pattern_idx: 0, sub_index: 0 },
      // No edge from 10 or 7 to 5
    ];
    const sp: VizPathGraph = {
      start_node: { index: 3, width: 1 },
      start_path: [],
      start_edges: [],
      root: { index: 10, width: 2 },
      root_edge: { from: 3, to: 10, pattern_idx: 0, sub_index: 0 },
      end_path: [{ index: 5, width: 1 }],
      end_edges: [{ from: 10, to: 5, pattern_idx: 0, sub_index: 0 }],
      cursor_pos: 0,
      done: false,
      success: false,
    };
    const { endKeys } = computeEdgeKeys(sp, edges);
    // Fallback: uses direct end_edges ref
    expect(endKeys.has(edgePairKey(10, 5))).toBe(true);
    expect(endKeys.size).toBe(1);
  });

  it('falls back to direct start edges when BFS fails', () => {
    // start_path[0] is not reachable from parent
    const edges: SnapshotEdge[] = [
      // No edge 7→3
      { from: 10, to: 7, pattern_idx: 0, sub_index: 0 },
    ];
    const sp: VizPathGraph = {
      start_node: { index: 3, width: 1 },
      start_path: [{ index: 7, width: 1 }],
      start_edges: [{ from: 3, to: 7, pattern_idx: 0, sub_index: 0 }],
      root: { index: 10, width: 2 },
      root_edge: { from: 7, to: 10, pattern_idx: 0, sub_index: 0 },
      end_path: [],
      end_edges: [],
      cursor_pos: 0,
      done: false,
      success: false,
    };
    const { startKeys } = computeEdgeKeys(sp, edges);
    // BFS from 7→3 fails (no edge), so fallback to direct edge (swapped): edgePairKey(7, 3)
    expect(startKeys.has(edgePairKey(7, 3))).toBe(true);
  });

  it('produces empty edge keys after parent rejection (empty end_path)', () => {
    // After parent rejection: end_path is cleared, start_path may change.
    // This simulates the state AFTER a parent is rejected — end_path is empty.
    const edges: SnapshotEdge[] = [
      { from: 10, to: 7, pattern_idx: 0, sub_index: 0 },
      { from: 7, to: 3, pattern_idx: 0, sub_index: 0 },
    ];
    const sp: VizPathGraph = {
      start_node: { index: 3, width: 1 },
      start_path: [{ index: 7, width: 1 }],
      start_edges: [{ from: 3, to: 7, pattern_idx: 0, sub_index: 0 }],
      root: { index: 10, width: 2 },
      root_edge: { from: 7, to: 10, pattern_idx: 0, sub_index: 0 },
      end_path: [],  // Cleared after rejection
      end_edges: [],
      cursor_pos: 0,
      done: false,
      success: false,
    };
    const { endKeys } = computeEdgeKeys(sp, edges);
    // No end path → no end edge keys
    expect(endKeys.size).toBe(0);
  });
});
