id = "88c88341-5f9c-4e59-87c7-9176e4afc26a"
created_at = "2026-06-06T16:14:36.422841400+00:00"
title = "temp"
state = "draft"
component = "viewer-api"
deleted = true
slug = "temp-review-probe"
type = "specification"
