//! Multiplayer Backend: shared types, table definitions, reducers, and auth.
//!
//! This module provides the client-side representation of the SpacetimeDB
//! server module. Types here mirror the server tables and reducer signatures
//! so the WASM client can serialize/deserialize multiplayer state.
//!
//! The actual SpacetimeDB server module lives in `tools/context-editor/server/`
//! and is compiled separately. This kernel module handles:
//! - Shared table types (Player, VoxelChunk, VoxelDelta, etc.)
//! - Client-side subscription state
//! - Reducer request/response types
//! - Auth identity management
//! - Game tick simulation for offline/singleplayer fallback

use bevy::prelude::*;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum interaction range for voxel editing (world units).
pub const MAX_INTERACTION_RANGE: f32 = 10.0;

/// Chunk size in voxels per axis (16³ chunks).
pub const CHUNK_SIZE: u32 = 16;

/// Game tick interval in milliseconds.
pub const TICK_INTERVAL_MS: u64 = 50;

/// Maximum inventory slots per player.
pub const MAX_INVENTORY_SLOTS: u8 = 40;

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/// Cryptographic player identity (mirrors SpacetimeDB `Identity`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct PlayerIdentity {
    /// 128-bit identity hash.
    pub id: u128,
}

impl PlayerIdentity {
    pub fn new(id: u128) -> Self {
        Self { id }
    }

    /// Generate a local-only identity for singleplayer mode.
    pub fn local() -> Self {
        Self { id: 1 }
    }
}

// ---------------------------------------------------------------------------
// Table types (shared between client and server)
// ---------------------------------------------------------------------------

/// A 16³ voxel chunk stored in the server database.
#[derive(Clone, Debug)]
pub struct VoxelChunk {
    /// Spatial hash from (cx, cy, cz).
    pub chunk_hash: u64,
    pub cx: i32,
    pub cy: i32,
    pub cz: i32,
    /// Serialized `OctreeNode` array for this chunk.
    pub octree_data: Vec<u8>,
    /// Tick number of last modification.
    pub last_modified: u64,
}

/// A single-voxel delta applied to a chunk.
#[derive(Clone, Debug)]
pub struct VoxelDelta {
    pub delta_id: u64,
    pub chunk_hash: u64,
    pub local_x: u8,
    pub local_y: u8,
    pub local_z: u8,
    pub new_color: u32,
    pub tick: u64,
}

/// Player state stored in the server database.
#[derive(Clone, Debug)]
pub struct PlayerRow {
    pub identity: PlayerIdentity,
    pub entity_id: u64,
    pub position: (f32, f32, f32),
    pub velocity: (f32, f32, f32),
    pub rotation_yaw: f32,
    pub hp: i32,
    pub max_hp: i32,
    pub mana: i32,
    pub max_mana: i32,
    pub skin_color: u32,
    pub last_tick: u64,
}

impl Default for PlayerRow {
    fn default() -> Self {
        Self {
            identity: PlayerIdentity::local(),
            entity_id: 0,
            position: (0.0, 10.0, 0.0),
            velocity: (0.0, 0.0, 0.0),
            rotation_yaw: 0.0,
            hp: 100,
            max_hp: 100,
            mana: 50,
            max_mana: 50,
            skin_color: 0xFFCCAA,
            last_tick: 0,
        }
    }
}

/// Item blueprint defining a craftable/equippable item.
#[derive(Clone, Debug)]
pub struct ItemBlueprint {
    pub blueprint_id: u32,
    pub name: String,
    /// Serialized 8³ mini-SVO for item appearance.
    pub voxel_data: Vec<u8>,
    pub base_damage: i32,
    pub weight: f32,
    pub item_type: ItemType,
}

/// Type classification for items.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum ItemType {
    Weapon = 0,
    Tool = 1,
    Block = 2,
    Consumable = 3,
}

impl ItemType {
    pub fn from_u8(v: u8) -> Self {
        match v {
            0 => Self::Weapon,
            1 => Self::Tool,
            2 => Self::Block,
            3 => Self::Consumable,
            _ => Self::Block,
        }
    }
}

/// A slot in a player's inventory.
#[derive(Clone, Debug)]
pub struct InventorySlot {
    pub slot_id: u64,
    pub owner: PlayerIdentity,
    pub blueprint_id: u32,
    pub quantity: u32,
    pub slot_index: u8,
}

/// Combat event generated by the server when an attack lands.
#[derive(Clone, Debug)]
pub struct CombatEvent {
    pub event_id: u64,
    pub attacker: PlayerIdentity,
    pub target: PlayerIdentity,
    pub damage: i32,
    pub hit_pos: (f32, f32, f32),
    pub tick: u64,
}

// ---------------------------------------------------------------------------
// Spatial hashing
// ---------------------------------------------------------------------------

/// Compute a spatial hash for chunk coordinates.
///
/// Uses FNV-1a–style mixing to distribute chunks across hash space.
pub fn spatial_hash(
    cx: i32,
    cy: i32,
    cz: i32,
) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for byte in cx
        .to_le_bytes()
        .iter()
        .chain(&cy.to_le_bytes())
        .chain(&cz.to_le_bytes())
    {
        h ^= *byte as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

/// Convert world voxel coordinates to chunk coordinates.
pub fn world_to_chunk(
    x: i32,
    y: i32,
    z: i32,
) -> (i32, i32, i32) {
    (
        x.div_euclid(CHUNK_SIZE as i32),
        y.div_euclid(CHUNK_SIZE as i32),
        z.div_euclid(CHUNK_SIZE as i32),
    )
}

/// Convert world voxel coordinates to local-within-chunk coordinates.
pub fn world_to_local(
    x: i32,
    y: i32,
    z: i32,
) -> (u8, u8, u8) {
    (
        x.rem_euclid(CHUNK_SIZE as i32) as u8,
        y.rem_euclid(CHUNK_SIZE as i32) as u8,
        z.rem_euclid(CHUNK_SIZE as i32) as u8,
    )
}

// ---------------------------------------------------------------------------
// Reducer request types
// ---------------------------------------------------------------------------

/// Client-sent reducer requests (serialized and sent to SpacetimeDB).
#[derive(Clone, Debug)]
pub enum ReducerRequest {
    UpdateVoxel {
        x: i32,
        y: i32,
        z: i32,
        new_color: u32,
    },
    PlayerMove {
        position: (f32, f32, f32),
        yaw: f32,
    },
    PerformAttack {
        direction: (f32, f32, f32),
        weapon_slot: u8,
    },
    PickupItem {
        item_entity_id: u64,
    },
    DropItem {
        slot_index: u8,
    },
    Respawn {
        position: (f32, f32, f32),
    },
}

/// Server response for reducer calls.
#[derive(Clone, Debug)]
pub enum ReducerResponse {
    Success,
    Error(String),
}

// ---------------------------------------------------------------------------
// Client-side subscription state (Bevy resources)
// ---------------------------------------------------------------------------

/// Tracks our local player identity and connection status.
#[derive(Resource)]
pub struct MultiplayerConnection {
    pub identity: PlayerIdentity,
    pub connected: bool,
    pub server_url: String,
    /// Current server tick (incremented by subscription updates).
    pub server_tick: u64,
}

impl Default for MultiplayerConnection {
    fn default() -> Self {
        Self {
            identity: PlayerIdentity::local(),
            connected: false,
            server_url: String::new(),
            server_tick: 0,
        }
    }
}

/// Client-side cache of all players from the server subscription.
#[derive(Resource, Default)]
pub struct PlayerTable {
    pub players: HashMap<PlayerIdentity, PlayerRow>,
}

impl PlayerTable {
    /// Get the local player's row.
    pub fn local_player(
        &self,
        identity: &PlayerIdentity,
    ) -> Option<&PlayerRow> {
        self.players.get(identity)
    }

    /// Number of online players.
    pub fn online_count(&self) -> usize {
        self.players.len()
    }
}

/// Client-side cache of item blueprints from the server.
#[derive(Resource, Default)]
pub struct BlueprintTable {
    pub blueprints: HashMap<u32, ItemBlueprint>,
}

/// Client-side inventory state.
#[derive(Resource, Default)]
pub struct InventoryTable {
    pub slots: Vec<InventorySlot>,
}

impl InventoryTable {
    /// Get items in a specific slot.
    pub fn get_slot(
        &self,
        index: u8,
    ) -> Option<&InventorySlot> {
        self.slots.iter().find(|s| s.slot_index == index)
    }

    /// Count occupied slots.
    pub fn occupied_count(&self) -> usize {
        self.slots.iter().filter(|s| s.quantity > 0).count()
    }
}

/// Queue of pending reducer requests to send to the server.
#[derive(Resource, Default)]
pub struct ReducerQueue {
    pub pending: Vec<ReducerRequest>,
}

impl ReducerQueue {
    pub fn push(
        &mut self,
        req: ReducerRequest,
    ) {
        self.pending.push(req);
    }

    pub fn drain(&mut self) -> Vec<ReducerRequest> {
        std::mem::take(&mut self.pending)
    }
}

/// Incoming combat events from server subscription.
#[derive(Resource, Default)]
pub struct CombatEventQueue {
    pub events: Vec<CombatEvent>,
}

// ---------------------------------------------------------------------------
// Validation helpers (client-side mirrors of server logic)
// ---------------------------------------------------------------------------

/// Validate that a player is within interaction range of a target position.
pub fn validate_interaction_range(
    player_pos: (f32, f32, f32),
    target: (f32, f32, f32),
) -> bool {
    let dx = player_pos.0 - target.0;
    let dy = player_pos.1 - target.1;
    let dz = player_pos.2 - target.2;
    (dx * dx + dy * dy + dz * dz).sqrt() <= MAX_INTERACTION_RANGE
}

/// Compute damage from weapon stats against a target.
pub fn compute_damage(
    base_damage: i32,
    weapon_weight: f32,
) -> i32 {
    let weight_bonus = (weapon_weight * 2.0) as i32;
    (base_damage + weight_bonus).max(1)
}

// ---------------------------------------------------------------------------
// Offline/singleplayer game tick
// ---------------------------------------------------------------------------

/// Tracks the local game tick for singleplayer fallback.
#[derive(Resource)]
pub struct LocalGameTick {
    pub tick: u64,
    pub timer_ms: f64,
}

impl Default for LocalGameTick {
    fn default() -> Self {
        Self {
            tick: 0,
            timer_ms: 0.0,
        }
    }
}

/// System: advance the local game tick at TICK_INTERVAL_MS when offline.
fn local_tick_system(
    time: Res<Time>,
    connection: Res<MultiplayerConnection>,
    mut tick: ResMut<LocalGameTick>,
) {
    if connection.connected {
        return; // Server drives the tick when online
    }

    tick.timer_ms += time.delta_secs_f64() * 1000.0;
    while tick.timer_ms >= TICK_INTERVAL_MS as f64 {
        tick.timer_ms -= TICK_INTERVAL_MS as f64;
        tick.tick += 1;
    }
}

/// System: drain the reducer queue (in singleplayer mode, apply locally).
fn drain_reducer_queue_system(
    connection: Res<MultiplayerConnection>,
    mut queue: ResMut<ReducerQueue>,
    mut players: ResMut<PlayerTable>,
) {
    if connection.connected {
        // In connected mode, a network transport system would send these
        // to SpacetimeDB. For now we just clear them.
        queue.pending.clear();
        return;
    }

    // Singleplayer: apply locally
    let requests = queue.drain();
    for req in requests {
        match req {
            ReducerRequest::PlayerMove { position, yaw } => {
                if let Some(player) =
                    players.players.get_mut(&connection.identity)
                {
                    player.position = position;
                    player.rotation_yaw = yaw;
                }
            },
            // Other reducers would need SVO access etc. — stubbed for now.
            _ => {},
        }
    }
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

/// Plugin registering multiplayer backend types and fallback tick systems.
pub struct MultiplayerBackendPlugin;

impl Plugin for MultiplayerBackendPlugin {
    fn build(
        &self,
        app: &mut App,
    ) {
        app.init_resource::<MultiplayerConnection>();
        app.init_resource::<PlayerTable>();
        app.init_resource::<BlueprintTable>();
        app.init_resource::<InventoryTable>();
        app.init_resource::<ReducerQueue>();
        app.init_resource::<CombatEventQueue>();
        app.init_resource::<LocalGameTick>();

        // Insert a default local player row
        let identity = PlayerIdentity::local();
        let mut player_table = PlayerTable::default();
        player_table.players.insert(identity, PlayerRow::default());
        app.insert_resource(player_table);

        app.add_systems(
            Update,
            (local_tick_system, drain_reducer_queue_system),
        );
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spatial_hash_deterministic() {
        let h1 = spatial_hash(1, 2, 3);
        let h2 = spatial_hash(1, 2, 3);
        assert_eq!(h1, h2);
    }

    #[test]
    fn spatial_hash_differs_for_different_coords() {
        let h1 = spatial_hash(0, 0, 0);
        let h2 = spatial_hash(1, 0, 0);
        let h3 = spatial_hash(0, 1, 0);
        assert_ne!(h1, h2);
        assert_ne!(h1, h3);
        assert_ne!(h2, h3);
    }

    #[test]
    fn world_to_chunk_positive() {
        assert_eq!(world_to_chunk(0, 0, 0), (0, 0, 0));
        assert_eq!(world_to_chunk(15, 15, 15), (0, 0, 0));
        assert_eq!(world_to_chunk(16, 0, 0), (1, 0, 0));
        assert_eq!(world_to_chunk(32, 48, 64), (2, 3, 4));
    }

    #[test]
    fn world_to_chunk_negative() {
        assert_eq!(world_to_chunk(-1, 0, 0), (-1, 0, 0));
        assert_eq!(world_to_chunk(-16, 0, 0), (-1, 0, 0));
        assert_eq!(world_to_chunk(-17, 0, 0), (-2, 0, 0));
    }

    #[test]
    fn world_to_local_positive() {
        assert_eq!(world_to_local(0, 0, 0), (0, 0, 0));
        assert_eq!(world_to_local(5, 10, 15), (5, 10, 15));
        assert_eq!(world_to_local(16, 0, 0), (0, 0, 0));
        assert_eq!(world_to_local(17, 0, 0), (1, 0, 0));
    }

    #[test]
    fn world_to_local_negative() {
        // -1 mod 16 = 15
        assert_eq!(world_to_local(-1, 0, 0), (15, 0, 0));
        assert_eq!(world_to_local(-16, 0, 0), (0, 0, 0));
    }

    #[test]
    fn validate_interaction_range_within() {
        assert!(validate_interaction_range((0.0, 0.0, 0.0), (5.0, 0.0, 0.0)));
    }

    #[test]
    fn validate_interaction_range_too_far() {
        assert!(!validate_interaction_range(
            (0.0, 0.0, 0.0),
            (20.0, 0.0, 0.0)
        ));
    }

    #[test]
    fn validate_interaction_range_exact_boundary() {
        assert!(validate_interaction_range(
            (0.0, 0.0, 0.0),
            (MAX_INTERACTION_RANGE, 0.0, 0.0)
        ));
    }

    #[test]
    fn compute_damage_minimum_one() {
        assert_eq!(compute_damage(0, 0.0), 1);
    }

    #[test]
    fn compute_damage_with_weight_bonus() {
        // base=10, weight=5.0 → bonus=10, total=20
        assert_eq!(compute_damage(10, 5.0), 20);
    }

    #[test]
    fn player_identity_local() {
        let id = PlayerIdentity::local();
        assert_eq!(id.id, 1);
    }

    #[test]
    fn player_table_online_count() {
        let mut table = PlayerTable::default();
        assert_eq!(table.online_count(), 0);
        table
            .players
            .insert(PlayerIdentity::new(1), PlayerRow::default());
        table
            .players
            .insert(PlayerIdentity::new(2), PlayerRow::default());
        assert_eq!(table.online_count(), 2);
    }

    #[test]
    fn inventory_occupied_count() {
        let mut inv = InventoryTable::default();
        inv.slots.push(InventorySlot {
            slot_id: 1,
            owner: PlayerIdentity::local(),
            blueprint_id: 100,
            quantity: 5,
            slot_index: 0,
        });
        inv.slots.push(InventorySlot {
            slot_id: 2,
            owner: PlayerIdentity::local(),
            blueprint_id: 200,
            quantity: 0, // empty
            slot_index: 1,
        });
        assert_eq!(inv.occupied_count(), 1);
    }

    #[test]
    fn reducer_queue_drain() {
        let mut queue = ReducerQueue::default();
        queue.push(ReducerRequest::PlayerMove {
            position: (1.0, 2.0, 3.0),
            yaw: 0.5,
        });
        queue.push(ReducerRequest::UpdateVoxel {
            x: 0,
            y: 0,
            z: 0,
            new_color: 0xFF0000,
        });
        let drained = queue.drain();
        assert_eq!(drained.len(), 2);
        assert!(queue.pending.is_empty());
    }

    #[test]
    fn item_type_roundtrip() {
        for v in 0..4u8 {
            let t = ItemType::from_u8(v);
            assert_eq!(t as u8, v);
        }
        // Unknown maps to Block
        assert_eq!(ItemType::from_u8(99), ItemType::Block);
    }

    #[test]
    fn local_game_tick_default() {
        let tick = LocalGameTick::default();
        assert_eq!(tick.tick, 0);
        assert_eq!(tick.timer_ms, 0.0);
    }

    #[test]
    fn combat_event_queue_default_empty() {
        let q = CombatEventQueue::default();
        assert!(q.events.is_empty());
    }
}
