id = "9e04ff58-9160-4766-b307-74c0fb32a92c"
created_at = "2026-06-05T22:14:17.119823700+00:00"
title = "handoff workflow prompts"
state = "draft"
component = "context-engine"
parent = "96dc0068-d05d-4e61-b785-144272119fa9"
scope = "internal"
slug = "context-engine/handoff-workflow-prompts"
type = "specification"
