//! MCP Server for context-engine hypergraph workspaces.
//!
//! Exposes the entire `context-api` command surface as a single MCP `execute`
//! tool. An MCP client sends a `Command` JSON object and receives a
//! `CommandResult` JSON object. The server runs over stdio transport using
//! `rmcp`, following the same pattern as `tools/log-viewer` and `tools/doc-viewer`.

use rmcp::{
    ErrorData as McpError,
    ServerHandler,
    ServiceExt,
    handler::server::{
        tool::ToolRouter,
        wrapper::Parameters,
    },
    model::*,
    schemars::{
        self,
        JsonSchema,
    },
    tool,
    tool_handler,
    tool_router,
    transport::stdio,
};
use serde::{
    Deserialize,
    Serialize,
};
use std::{
    path::PathBuf,
    sync::{
        Arc,
        Mutex,
    },
};

use context_api::{
    commands::{
        Command,
        CommandResult,
        execute,
    },
    workspace::manager::WorkspaceManager,
};

/// MCP Server for context-engine hypergraph operations.
///
/// Wraps a `WorkspaceManager` in `Arc<Mutex<>>` for interior mutability
/// (MCP tool handlers receive `&self` but `execute()` needs `&mut`).
/// The Mutex is appropriate because stdio MCP processes one tool call at a
/// time.
#[derive(Clone)]
pub struct ContextServer {
    /// Shared workspace manager.
    manager: Arc<Mutex<WorkspaceManager>>,
    tool_router: ToolRouter<Self>,
}

impl ContextServer {
    /// Create a new server rooted at the given base directory.
    ///
    /// Workspaces will be stored under `<base_dir>/.context-engine/`.
    pub fn new(base_dir: PathBuf) -> Self {
        let manager = WorkspaceManager::new(base_dir);
        Self {
            manager: Arc::new(Mutex::new(manager)),
            tool_router: Self::tool_router(),
        }
    }
}

// ---------------------------------------------------------------------------
// Tool input / output types
// ---------------------------------------------------------------------------

/// Input schema for the `execute` tool.
///
/// The `command` field is the full `Command` enum — its JSON schema is
/// auto-generated by schemars and documents every command variant and its
/// fields for the MCP client.
///
/// Because of `#[serde(flatten)]` the input JSON **is** the command itself
/// (no extra wrapping layer). For example:
///
/// ```json
/// {"command": "create_workspace", "name": "demo"}
/// ```
#[derive(Debug, Deserialize, JsonSchema)]
pub struct ExecuteInput {
    /// The command to execute. See the schema for all available commands.
    ///
    /// Examples:
    /// - `{"command": "create_workspace", "name": "my-graph"}`
    /// - `{"command": "add_atoms", "workspace": "my-graph", "chars": ["a","b","c"]}`
    /// - `{"command": "insert_sequence", "workspace": "my-graph", "text": "hello"}`
    /// - `{"command": "search_sequence", "workspace": "my-graph", "text": "hel"}`
    /// - `{"command": "read_as_text", "workspace": "my-graph", "index": 3}`
    /// - `{"command": "save_workspace", "name": "my-graph"}`
    #[serde(flatten)]
    pub command: Command,
}

/// Output wrapper for the `execute` tool.
///
/// API-level errors are returned as `success: false` with an `error` message
/// (not as MCP-level errors) so the agent can read and react to them.
#[derive(Debug, Serialize, Deserialize)]
pub struct ExecuteOutput {
    /// Whether the command succeeded.
    pub success: bool,
    /// The result (present when `success` is `true`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<CommandResult>,
    /// Error message (present when `success` is `false`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

// ---------------------------------------------------------------------------
// Tool implementation
// ---------------------------------------------------------------------------

#[tool_router]
impl ContextServer {
    /// Execute a context-engine command against a hypergraph workspace.
    ///
    /// This is the single entry point for all operations: workspace lifecycle,
    /// atom/pattern creation, search, insert, read, and debug commands.
    ///
    /// ## Workflow Example
    ///
    /// 1. Create a workspace: `{"command": "create_workspace", "name": "demo"}`
    /// 2. Add atoms: `{"command": "add_atoms", "workspace": "demo", "chars": ["a","b","c","d","e"]}`
    /// 3. Insert a sequence: `{"command": "insert_sequence", "workspace": "demo", "text": "abcde"}`
    /// 4. Search: `{"command": "search_sequence", "workspace": "demo", "text": "abc"}`
    /// 5. Read: `{"command": "read_as_text", "workspace": "demo", "index": 5}`
    /// 6. Save: `{"command": "save_workspace", "name": "demo"}`
    ///
    /// ## Available Commands
    ///
    /// **Workspace:** create_workspace, open_workspace, close_workspace,
    /// save_workspace, list_workspaces, delete_workspace
    ///
    /// **Atoms:** add_atom, add_atoms, get_atom, list_atoms
    ///
    /// **Patterns:** add_simple_pattern, get_vertex, list_vertices
    ///
    /// **Search:** search_pattern, search_sequence
    ///
    /// **Insert:** insert_first_match, insert_sequence, insert_sequences
    ///
    /// **Read:** read_pattern, read_as_text
    ///
    /// **Debug:** get_snapshot, get_statistics, validate_graph, show_graph, show_vertex
    #[tool(
        name = "execute",
        description = "Execute a context-engine hypergraph command. Send any Command JSON object and receive the corresponding CommandResult."
    )]
    async fn execute_command(
        &self,
        Parameters(input): Parameters<ExecuteInput>,
    ) -> Result<CallToolResult, McpError> {
        tracing::debug!(command = ?input.command, "Executing command");

        let result = {
            let mut manager = self.manager.lock().map_err(|e| {
                McpError::internal_error(format!("Lock poisoned: {e}"), None)
            })?;
            execute(&mut manager, input.command)
        };

        match result {
            Ok(cmd_result) => {
                let output = ExecuteOutput {
                    success: true,
                    result: Some(cmd_result),
                    error: None,
                };
                let json =
                    serde_json::to_string_pretty(&output).map_err(|e| {
                        McpError::internal_error(
                            format!("Serialization failed: {e}"),
                            None,
                        )
                    })?;
                Ok(CallToolResult::success(vec![Content::text(json)]))
            },
            Err(api_error) => {
                tracing::warn!(error = %api_error, "Command failed");
                let output = ExecuteOutput {
                    success: false,
                    result: None,
                    error: Some(format!("{api_error}")),
                };
                let json =
                    serde_json::to_string_pretty(&output).map_err(|e| {
                        McpError::internal_error(
                            format!("Serialization failed: {e}"),
                            None,
                        )
                    })?;
                // Return as a successful MCP response with an error payload
                // so the agent can read and react to the error message.
                Ok(CallToolResult::success(vec![Content::text(json)]))
            },
        }
    }
}

// ---------------------------------------------------------------------------
// ServerHandler (MCP metadata)
// ---------------------------------------------------------------------------

#[tool_handler]
impl ServerHandler for ContextServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            instructions: Some(
                "Context Engine MCP Server — manages hypergraph workspaces.\n\n\
                 Use the 'execute' tool with a command JSON object.\n\
                 Start by creating or opening a workspace, then add atoms,\n\
                 insert sequences, search patterns, and read results.\n\
                 Remember to save_workspace before ending the session.\n\n\
                 Quick start:\n\
                 1. {\"command\": \"create_workspace\", \"name\": \"demo\"}\n\
                 2. {\"command\": \"add_atoms\", \"workspace\": \"demo\", \"chars\": [\"a\",\"b\",\"c\"]}\n\
                 3. {\"command\": \"insert_sequence\", \"workspace\": \"demo\", \"text\": \"abc\"}\n\
                 4. {\"command\": \"search_sequence\", \"workspace\": \"demo\", \"text\": \"ab\"}\n\
                 5. {\"command\": \"save_workspace\", \"name\": \"demo\"}"
                    .to_string(),
            ),
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            ..Default::default()
        }
    }
}

// ---------------------------------------------------------------------------
// Server launcher
// ---------------------------------------------------------------------------

/// Run the MCP server on stdio transport.
///
/// This blocks until the MCP client disconnects (stdin EOF).
pub async fn run_mcp_server(
    base_dir: PathBuf
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let server = ContextServer::new(base_dir);

    tracing::info!("Starting context-mcp server on stdio");

    let service = server.serve(stdio()).await.inspect_err(|e| {
        eprintln!("Server error: {:?}", e);
    })?;

    service.waiting().await?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use context_api::commands::Command;
    use rmcp::model::RawContent;

    /// Helper: create a server backed by a temporary directory.
    fn tmp_server() -> (tempfile::TempDir, ContextServer) {
        let tmp = tempfile::tempdir().expect("create temp dir");
        let server = ContextServer::new(tmp.path().to_path_buf());
        (tmp, server)
    }

    /// Parse the text content of a `CallToolResult` into an `ExecuteOutput`.
    fn parse_output(result: &CallToolResult) -> ExecuteOutput {
        let content =
            result.content.first().expect("result should have content");
        match &content.raw {
            RawContent::Text(text_content) =>
                serde_json::from_str(&text_content.text)
                    .expect("should parse as ExecuteOutput"),
            _ => panic!("Expected text content"),
        }
    }

    /// Helper to execute a command via the server and return the parsed output.
    async fn exec(
        server: &ContextServer,
        command: Command,
    ) -> ExecuteOutput {
        let input = Parameters(ExecuteInput { command });
        let result = server
            .execute_command(input)
            .await
            .expect("MCP call should not fail");
        parse_output(&result)
    }

    #[tokio::test]
    async fn test_create_workspace() {
        let (_tmp, server) = tmp_server();

        let output = exec(
            &server,
            Command::CreateWorkspace {
                name: "test".into(),
            },
        )
        .await;

        assert!(output.success, "create_workspace should succeed");
        assert!(output.result.is_some());
        assert!(output.error.is_none());
    }

    #[tokio::test]
    async fn test_error_workspace_not_found() {
        let (_tmp, server) = tmp_server();

        // Try to open a workspace that doesn't exist
        let output = exec(
            &server,
            Command::OpenWorkspace {
                name: "nope".into(),
            },
        )
        .await;

        assert!(!output.success, "open nonexistent should fail");
        assert!(output.result.is_none());
        assert!(output.error.is_some());
        assert!(
            output.error.as_ref().unwrap().contains("not found"),
            "error should mention 'not found': {:?}",
            output.error
        );
    }

    #[tokio::test]
    async fn test_add_atoms_and_list() {
        let (_tmp, server) = tmp_server();

        // Create workspace
        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;

        // Add atoms
        let output = exec(
            &server,
            Command::AddAtoms {
                workspace: "ws".into(),
                chars: vec!['a', 'b', 'c'],
            },
        )
        .await;
        assert!(output.success, "add_atoms should succeed");

        // List atoms
        let output = exec(
            &server,
            Command::ListAtoms {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success, "list_atoms should succeed");

        // Verify we got an AtomInfoList
        match &output.result {
            Some(CommandResult::AtomInfoList { atoms }) => {
                assert_eq!(atoms.len(), 3, "should have 3 atoms");
            },
            other => panic!("Expected AtomInfoList, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_insert_and_search_workflow() {
        let (_tmp, server) = tmp_server();

        // Create workspace
        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;

        // Insert a sequence (auto-creates atoms)
        let output = exec(
            &server,
            Command::InsertSequence {
                workspace: "ws".into(),
                text: "hello".into(),
            },
        )
        .await;
        assert!(output.success, "insert should succeed: {:?}", output.error);

        // Verify insert result — the engine returns an InsertResult with a
        // token. Due to algorithmic semantics (is_entire_root / prefix match),
        // `already_existed` may be true or false depending on graph state.
        match &output.result {
            Some(CommandResult::InsertResult(ir)) => {
                assert!(
                    !ir.token.label.is_empty(),
                    "token label should not be empty"
                );
            },
            other => panic!("Expected InsertResult, got {other:?}"),
        }

        // Search for it — the search should succeed (return a SearchResult)
        let output = exec(
            &server,
            Command::SearchSequence {
                workspace: "ws".into(),
                text: "hello".into(),
            },
        )
        .await;
        assert!(output.success, "search should succeed: {:?}", output.error);

        match &output.result {
            Some(CommandResult::SearchResult(_sr)) => {
                // Search returned a result — the exact semantics (complete
                // vs partial) depend on how insert built the graph.
            },
            other => panic!("Expected SearchResult, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_statistics() {
        let (_tmp, server) = tmp_server();

        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;
        exec(
            &server,
            Command::AddAtoms {
                workspace: "ws".into(),
                chars: vec!['x', 'y'],
            },
        )
        .await;

        let output = exec(
            &server,
            Command::GetStatistics {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success);

        match &output.result {
            Some(CommandResult::Statistics(stats)) => {
                assert_eq!(stats.atom_count, 2);
                assert_eq!(stats.vertex_count, 2);
            },
            other => panic!("Expected Statistics, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_save_close_reopen_persistence() {
        let (_tmp, server) = tmp_server();

        // Create workspace
        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;

        // Add atoms and insert — use add_atoms + add_simple_pattern for a
        // deterministic graph structure that survives round-trip serialization.
        exec(
            &server,
            Command::AddAtoms {
                workspace: "ws".into(),
                chars: vec!['a', 'b', 'c'],
            },
        )
        .await;
        exec(
            &server,
            Command::AddSimplePattern {
                workspace: "ws".into(),
                atoms: vec!['a', 'b'],
            },
        )
        .await;

        // Check stats before save
        let output = exec(
            &server,
            Command::GetStatistics {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success);
        let before_count = match &output.result {
            Some(CommandResult::Statistics(s)) => s.vertex_count,
            other => panic!("Expected Statistics, got {other:?}"),
        };
        assert!(before_count >= 3, "should have at least 3 atoms");

        // Save, close
        exec(&server, Command::SaveWorkspace { name: "ws".into() }).await;
        exec(&server, Command::CloseWorkspace { name: "ws".into() }).await;

        // Reopen
        let output =
            exec(&server, Command::OpenWorkspace { name: "ws".into() }).await;
        assert!(output.success, "reopen should succeed: {:?}", output.error);

        // Verify the graph was persisted — vertex count should be the same
        let output = exec(
            &server,
            Command::GetStatistics {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success);
        let after_count = match &output.result {
            Some(CommandResult::Statistics(s)) => s.vertex_count,
            other => panic!("Expected Statistics, got {other:?}"),
        };
        assert_eq!(
            before_count, after_count,
            "vertex count should survive save+close+reopen"
        );
    }

    #[tokio::test]
    async fn test_list_workspaces() {
        let (_tmp, server) = tmp_server();

        let output = exec(&server, Command::ListWorkspaces).await;
        assert!(output.success);

        match &output.result {
            Some(CommandResult::WorkspaceInfoList { workspaces }) => {
                assert!(
                    workspaces.is_empty(),
                    "no workspaces yet: {workspaces:?}"
                );
            },
            other => panic!("Expected WorkspaceInfoList, got {other:?}"),
        }

        // Create one, then list again
        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;
        exec(&server, Command::SaveWorkspace { name: "ws".into() }).await;

        let output = exec(&server, Command::ListWorkspaces).await;
        assert!(output.success);

        match &output.result {
            Some(CommandResult::WorkspaceInfoList { workspaces }) => {
                assert_eq!(workspaces.len(), 1);
                assert_eq!(workspaces[0].name, "ws");
            },
            other => panic!("Expected WorkspaceInfoList, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_execute_input_serde_flatten() {
        // Verify that ExecuteInput with serde(flatten) deserializes correctly
        let json = r#"{"command": "create_workspace", "name": "demo"}"#;
        let input: ExecuteInput =
            serde_json::from_str(json).expect("should deserialize");
        match input.command {
            Command::CreateWorkspace { name } => {
                assert_eq!(name, "demo");
            },
            other => panic!("Expected CreateWorkspace, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_execute_input_serde_complex() {
        let json = r#"{"command": "insert_sequence", "workspace": "ws", "text": "hello world"}"#;
        let input: ExecuteInput =
            serde_json::from_str(json).expect("should deserialize");
        match input.command {
            Command::InsertSequence { workspace, text } => {
                assert_eq!(workspace, "ws");
                assert_eq!(text, "hello world");
            },
            other => panic!("Expected InsertSequence, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_validate_graph() {
        let (_tmp, server) = tmp_server();

        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;

        let output = exec(
            &server,
            Command::ValidateGraph {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success);

        match &output.result {
            Some(CommandResult::ValidationReport(report)) => {
                assert!(report.valid, "empty graph should be valid");
            },
            other => panic!("Expected ValidationReport, got {other:?}"),
        }
    }
}
