//! MCP Server for context-engine hypergraph workspaces.
//!
//! Exposes the `context-api` command surface through three MCP tools:
//!
//! - **`execute`** — Run any context-engine command (the primary workhorse).
//! - **`help`** — Discover available commands, grouped by category, with
//!   examples and parameter descriptions. Agents should call this first.
//! - **`workflow`** — Get ready-to-use command sequences for common tasks
//!   (basic setup, bulk insert, search & read, etc.).
//!
//! The server runs over stdio transport using `rmcp`, following the same
//! pattern as `tools/log-viewer` and `tools/doc-viewer`.

use rmcp::{
    ErrorData as McpError,
    ServerHandler,
    ServiceExt,
    handler::server::{
        tool::ToolRouter,
        wrapper::Parameters,
    },
    model::*,
    schemars::{
        self,
        JsonSchema,
    },
    tool,
    tool_handler,
    tool_router,
    transport::stdio,
};
use serde::{
    Deserialize,
    Serialize,
};
use std::{
    path::PathBuf,
    sync::{
        Arc,
        Mutex,
    },
};

use context_api::{
    commands::{
        Command,
        CommandResult,
        execute,
    },
    workspace::manager::WorkspaceManager,
};

/// MCP Server for context-engine hypergraph operations.
///
/// Wraps a `WorkspaceManager` in `Arc<Mutex<>>` for interior mutability
/// (MCP tool handlers receive `&self` but `execute()` needs `&mut`).
/// The Mutex is appropriate because stdio MCP processes one tool call at a
/// time.
#[derive(Clone)]
pub struct ContextServer {
    /// Shared workspace manager.
    manager: Arc<Mutex<WorkspaceManager>>,
    tool_router: ToolRouter<Self>,
}

impl ContextServer {
    /// Create a new server rooted at the given base directory.
    ///
    /// Workspaces will be stored under `<base_dir>/.context-engine/`.
    pub fn new(base_dir: PathBuf) -> Self {
        let manager = WorkspaceManager::new(base_dir);
        Self {
            manager: Arc::new(Mutex::new(manager)),
            tool_router: Self::tool_router(),
        }
    }
}

// ---------------------------------------------------------------------------
// Tool input / output types
// ---------------------------------------------------------------------------

/// Input schema for the `execute` tool.
///
/// The `command` field is the full `Command` enum — its JSON schema is
/// auto-generated by schemars and documents every command variant and its
/// fields for the MCP client.
///
/// Because of `#[serde(flatten)]` the input JSON **is** the command itself
/// (no extra wrapping layer). For example:
///
/// ```json
/// {"command": "create_workspace", "name": "demo"}
/// ```
#[derive(Debug, Deserialize, JsonSchema)]
pub struct ExecuteInput {
    /// The command to execute. See the schema for all available commands.
    ///
    /// Examples:
    /// - `{"command": "create_workspace", "name": "my-graph"}`
    /// - `{"command": "add_atoms", "workspace": "my-graph", "chars": ["a","b","c"]}`
    /// - `{"command": "insert_sequence", "workspace": "my-graph", "text": "hello"}`
    /// - `{"command": "search_sequence", "workspace": "my-graph", "text": "hel"}`
    /// - `{"command": "read_as_text", "workspace": "my-graph", "index": 3}`
    /// - `{"command": "save_workspace", "name": "my-graph"}`
    #[serde(flatten)]
    pub command: Command,
}

/// Output wrapper for the `execute` tool.
///
/// API-level errors are returned as `success: false` with an `error` message
/// (not as MCP-level errors) so the agent can read and react to them.
#[derive(Debug, Serialize, Deserialize)]
pub struct ExecuteOutput {
    /// Whether the command succeeded.
    pub success: bool,
    /// The result (present when `success` is `true`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<CommandResult>,
    /// Error message (present when `success` is `false`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Input schema for the `help` tool.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct HelpInput {
    /// Optional: a specific command name to get detailed help for.
    /// If omitted, returns an overview of all commands grouped by category.
    ///
    /// Examples: "create_workspace", "insert_sequence", "search_sequence"
    #[serde(default)]
    pub command: Option<String>,

    /// Optional: a category name to list only that category's commands.
    /// If omitted (and no specific command requested), returns all categories.
    ///
    /// Valid categories: "workspace", "atoms", "patterns", "search", "insert", "read", "debug"
    #[serde(default)]
    pub category: Option<String>,
}

/// Input schema for the `workflow` tool.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct WorkflowInput {
    /// The workflow template to retrieve.
    /// Use "list" (or omit) to see all available workflows.
    ///
    /// Available workflows:
    /// - "list" — List all available workflow templates
    /// - "basic" — Create workspace, add atoms, insert, search, read, save
    /// - "bulk_insert" — Insert multiple sequences efficiently
    /// - "search_and_read" — Search for patterns and read results
    /// - "inspect" — Debug and inspect graph state
    /// - "persistence" — Save, close, reopen workflow
    #[serde(default = "default_workflow_name")]
    pub name: String,

    /// Workspace name to substitute into the template commands.
    /// Defaults to "demo" if not provided.
    #[serde(default = "default_workspace_name")]
    pub workspace: String,
}

fn default_workflow_name() -> String {
    "list".to_string()
}

fn default_workspace_name() -> String {
    "demo".to_string()
}

// ---------------------------------------------------------------------------
// Help content (static reference data)
// ---------------------------------------------------------------------------

/// A single command's help information.
#[derive(Debug, Serialize)]
struct CommandHelp {
    name: &'static str,
    category: &'static str,
    summary: &'static str,
    parameters: &'static [ParamHelp],
    example: &'static str,
    result_type: &'static str,
    notes: &'static str,
}

/// A parameter description for a command.
#[derive(Debug, Serialize)]
struct ParamHelp {
    name: &'static str,
    #[serde(rename = "type")]
    param_type: &'static str,
    required: bool,
    description: &'static str,
}

/// All command help entries, in category order.
fn all_commands() -> Vec<CommandHelp> {
    vec![
        // -- Workspace lifecycle --
        CommandHelp {
            name: "create_workspace",
            category: "workspace",
            summary: "Create a new empty workspace.",
            parameters: &[ParamHelp {
                name: "name",
                param_type: "string",
                required: true,
                description: "Name for the new workspace.",
            }],
            example: r#"{"command": "create_workspace", "name": "my-graph"}"#,
            result_type: "WorkspaceInfo",
            notes: "Fails if a workspace with the same name already exists in memory.",
        },
        CommandHelp {
            name: "open_workspace",
            category: "workspace",
            summary: "Open a previously saved workspace from disk.",
            parameters: &[ParamHelp {
                name: "name",
                param_type: "string",
                required: true,
                description: "Name of the workspace to open.",
            }],
            example: r#"{"command": "open_workspace", "name": "my-graph"}"#,
            result_type: "WorkspaceInfo",
            notes: "Loads from <base_dir>/.context-engine/<name>/. Fails if not found on disk.",
        },
        CommandHelp {
            name: "close_workspace",
            category: "workspace",
            summary: "Close a workspace (remove from memory). Does NOT auto-save.",
            parameters: &[ParamHelp {
                name: "name",
                param_type: "string",
                required: true,
                description: "Name of the workspace to close.",
            }],
            example: r#"{"command": "close_workspace", "name": "my-graph"}"#,
            result_type: "Ok",
            notes: "Remember to save_workspace first if you want to keep changes!",
        },
        CommandHelp {
            name: "save_workspace",
            category: "workspace",
            summary: "Save a workspace to disk.",
            parameters: &[ParamHelp {
                name: "name",
                param_type: "string",
                required: true,
                description: "Name of the workspace to save.",
            }],
            example: r#"{"command": "save_workspace", "name": "my-graph"}"#,
            result_type: "Ok",
            notes: "Persists to <base_dir>/.context-engine/<name>/. Always save before closing.",
        },
        CommandHelp {
            name: "list_workspaces",
            category: "workspace",
            summary: "List all workspaces currently open in memory.",
            parameters: &[],
            example: r#"{"command": "list_workspaces"}"#,
            result_type: "WorkspaceInfoList",
            notes: "Only shows in-memory workspaces. Saved-but-closed workspaces won't appear.",
        },
        CommandHelp {
            name: "delete_workspace",
            category: "workspace",
            summary: "Delete a workspace from memory and disk.",
            parameters: &[ParamHelp {
                name: "name",
                param_type: "string",
                required: true,
                description: "Name of the workspace to delete.",
            }],
            example: r#"{"command": "delete_workspace", "name": "old-graph"}"#,
            result_type: "Ok",
            notes: "Irreversible. Removes both in-memory state and on-disk files.",
        },
        // -- Atoms --
        CommandHelp {
            name: "add_atom",
            category: "atoms",
            summary: "Add a single character atom to the graph.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "ch",
                    param_type: "char",
                    required: true,
                    description: "The character to add (single character string).",
                },
            ],
            example: r#"{"command": "add_atom", "workspace": "demo", "ch": "a"}"#,
            result_type: "AtomInfo { index, ch }",
            notes: "Idempotent — adding the same character twice returns the existing atom.",
        },
        CommandHelp {
            name: "add_atoms",
            category: "atoms",
            summary: "Add multiple character atoms at once.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "chars",
                    param_type: "array of char",
                    required: true,
                    description: "Characters to add (e.g., [\"a\", \"b\", \"c\"]).",
                },
            ],
            example: r#"{"command": "add_atoms", "workspace": "demo", "chars": ["a","b","c","d","e"]}"#,
            result_type: "AtomInfoList { atoms: [AtomInfo] }",
            notes: "Recommended before insert_sequence — add all unique characters your text uses.",
        },
        CommandHelp {
            name: "get_atom",
            category: "atoms",
            summary: "Look up an atom by its character.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "ch",
                    param_type: "char",
                    required: true,
                    description: "The character to look up.",
                },
            ],
            example: r#"{"command": "get_atom", "workspace": "demo", "ch": "a"}"#,
            result_type: "OptionalAtomInfo { atom: AtomInfo | null }",
            notes: "Returns null if the character hasn't been added as an atom.",
        },
        CommandHelp {
            name: "list_atoms",
            category: "atoms",
            summary: "List all atoms in the workspace.",
            parameters: &[ParamHelp {
                name: "workspace",
                param_type: "string",
                required: true,
                description: "Target workspace name.",
            }],
            example: r#"{"command": "list_atoms", "workspace": "demo"}"#,
            result_type: "AtomInfoList { atoms: [AtomInfo] }",
            notes: "Atoms are the leaf nodes of the graph — each represents one character.",
        },
        // -- Patterns --
        CommandHelp {
            name: "add_simple_pattern",
            category: "patterns",
            summary: "Create a pattern (compound vertex) from a sequence of atom characters.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "atoms",
                    param_type: "array of char",
                    required: true,
                    description: "Ordered characters forming the pattern (e.g., [\"a\", \"b\"]).",
                },
            ],
            example: r#"{"command": "add_simple_pattern", "workspace": "demo", "atoms": ["a","b"]}"#,
            result_type: "PatternInfo { index, label, width, children }",
            notes: "Low-level. Prefer insert_sequence for text — it handles atom creation and hierarchy.",
        },
        CommandHelp {
            name: "get_vertex",
            category: "patterns",
            summary: "Get detailed information about a vertex by its index.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "index",
                    param_type: "integer",
                    required: true,
                    description: "Vertex index to look up.",
                },
            ],
            example: r#"{"command": "get_vertex", "workspace": "demo", "index": 5}"#,
            result_type: "OptionalVertexInfo { vertex: VertexInfo | null }",
            notes: "Returns label, width, is_atom flag, children indices, and parent count.",
        },
        CommandHelp {
            name: "list_vertices",
            category: "patterns",
            summary: "List all vertices (atoms and patterns) in the graph.",
            parameters: &[ParamHelp {
                name: "workspace",
                param_type: "string",
                required: true,
                description: "Target workspace name.",
            }],
            example: r#"{"command": "list_vertices", "workspace": "demo"}"#,
            result_type: "TokenInfoList { tokens: [TokenInfo] }",
            notes: "Can be large — use get_statistics first to check vertex_count.",
        },
        // -- Search --
        CommandHelp {
            name: "search_pattern",
            category: "search",
            summary: "Search for a pattern using token references (index or label).",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "query",
                    param_type: "array of TokenRef",
                    required: true,
                    description: r#"Sequence of token references. Each is {"index": N} or {"label": "text"}."#,
                },
            ],
            example: r#"{"command": "search_pattern", "workspace": "demo", "query": [{"label": "ab"}, {"label": "c"}]}"#,
            result_type: "SearchResult { complete, token, query_exhausted, partial }",
            notes: "Advanced — use search_sequence for text-based queries instead.",
        },
        CommandHelp {
            name: "search_sequence",
            category: "search",
            summary: "Search for a text string in the graph.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "text",
                    param_type: "string",
                    required: true,
                    description: "Text to search for.",
                },
            ],
            example: r#"{"command": "search_sequence", "workspace": "demo", "text": "abc"}"#,
            result_type: "SearchResult { complete, token, query_exhausted, partial }",
            notes: "Returns complete=true if the entire text exists as a single token. Check partial for prefix/postfix matches.",
        },
        // -- Insert --
        CommandHelp {
            name: "insert_first_match",
            category: "insert",
            summary: "Insert a pattern using token references (advanced).",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "query",
                    param_type: "array of TokenRef",
                    required: true,
                    description: r#"Sequence of token references to insert."#,
                },
            ],
            example: r#"{"command": "insert_first_match", "workspace": "demo", "query": [{"index": 0}, {"index": 1}]}"#,
            result_type: "InsertResult { token, already_existed }",
            notes: "Advanced — prefer insert_sequence for text.",
        },
        CommandHelp {
            name: "insert_sequence",
            category: "insert",
            summary: "Insert a text string into the graph, creating all necessary hierarchy.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "text",
                    param_type: "string",
                    required: true,
                    description: "Text to insert.",
                },
            ],
            example: r#"{"command": "insert_sequence", "workspace": "demo", "text": "hello"}"#,
            result_type: "InsertResult { token: TokenInfo, already_existed: bool }",
            notes: "The primary insertion command. Atoms must exist first (use add_atoms). Returns already_existed=true if the exact sequence was already in the graph.",
        },
        CommandHelp {
            name: "insert_sequences",
            category: "insert",
            summary: "Insert multiple text strings at once.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "texts",
                    param_type: "array of string (set)",
                    required: true,
                    description: "Set of texts to insert (duplicates ignored).",
                },
            ],
            example: r#"{"command": "insert_sequences", "workspace": "demo", "texts": ["hello", "world"]}"#,
            result_type: "InsertResultList { results: [InsertResult] }",
            notes: "More efficient than calling insert_sequence repeatedly. Order is not guaranteed.",
        },
        // -- Read --
        CommandHelp {
            name: "read_pattern",
            category: "read",
            summary: "Read the full tree structure rooted at a vertex.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "index",
                    param_type: "integer",
                    required: true,
                    description: "Root vertex index to read from.",
                },
            ],
            example: r#"{"command": "read_pattern", "workspace": "demo", "index": 5}"#,
            result_type: "ReadResult { root: TokenInfo, text: string, tree: ReadNode }",
            notes: "Returns the hierarchical decomposition of the token into its children.",
        },
        CommandHelp {
            name: "read_as_text",
            category: "read",
            summary: "Read the text representation of a vertex (concatenation of its leaf atoms).",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "index",
                    param_type: "integer",
                    required: true,
                    description: "Vertex index to read.",
                },
            ],
            example: r#"{"command": "read_as_text", "workspace": "demo", "index": 5}"#,
            result_type: "Text { text: string }",
            notes: "The simplest way to see what text a vertex represents.",
        },
        // -- Debug --
        CommandHelp {
            name: "get_snapshot",
            category: "debug",
            summary: "Get a full snapshot of the graph (for debugging/inspection).",
            parameters: &[ParamHelp {
                name: "workspace",
                param_type: "string",
                required: true,
                description: "Target workspace name.",
            }],
            example: r#"{"command": "get_snapshot", "workspace": "demo"}"#,
            result_type: "Snapshot (JSON object)",
            notes: "Can be very large for big graphs. Use get_statistics for a quick summary instead.",
        },
        CommandHelp {
            name: "get_statistics",
            category: "debug",
            summary: "Get summary statistics about the graph.",
            parameters: &[ParamHelp {
                name: "workspace",
                param_type: "string",
                required: true,
                description: "Target workspace name.",
            }],
            example: r#"{"command": "get_statistics", "workspace": "demo"}"#,
            result_type: "Statistics { vertex_count, atom_count, pattern_count, max_width, edge_count }",
            notes: "Lightweight — always safe to call. Good for checking graph size before list_vertices.",
        },
        CommandHelp {
            name: "validate_graph",
            category: "debug",
            summary: "Run integrity validation on the graph.",
            parameters: &[ParamHelp {
                name: "workspace",
                param_type: "string",
                required: true,
                description: "Target workspace name.",
            }],
            example: r#"{"command": "validate_graph", "workspace": "demo"}"#,
            result_type: "ValidationReport { valid: bool, vertex_count, issues: [string] }",
            notes: "Checks for structural issues. Empty issues array means the graph is healthy.",
        },
        CommandHelp {
            name: "show_graph",
            category: "debug",
            summary: "Get a human-readable text display of the entire graph.",
            parameters: &[ParamHelp {
                name: "workspace",
                param_type: "string",
                required: true,
                description: "Target workspace name.",
            }],
            example: r#"{"command": "show_graph", "workspace": "demo"}"#,
            result_type: "GraphDisplay { display: string }",
            notes: "Useful for understanding graph structure. Can be large.",
        },
        CommandHelp {
            name: "show_vertex",
            category: "debug",
            summary: "Get a human-readable text display of a single vertex and its neighborhood.",
            parameters: &[
                ParamHelp {
                    name: "workspace",
                    param_type: "string",
                    required: true,
                    description: "Target workspace name.",
                },
                ParamHelp {
                    name: "index",
                    param_type: "integer",
                    required: true,
                    description: "Vertex index to display.",
                },
            ],
            example: r#"{"command": "show_vertex", "workspace": "demo", "index": 3}"#,
            result_type: "GraphDisplay { display: string }",
            notes: "More focused than show_graph — shows one vertex with its parents and children.",
        },
    ]
}

/// Category metadata for the overview.
struct CategoryInfo {
    name: &'static str,
    display: &'static str,
    description: &'static str,
}

fn all_categories() -> Vec<CategoryInfo> {
    vec![
        CategoryInfo {
            name: "workspace",
            display: "Workspace Lifecycle",
            description: "Create, open, save, close, and delete workspaces.",
        },
        CategoryInfo {
            name: "atoms",
            display: "Atoms",
            description: "Manage character atoms — the leaf nodes of the hypergraph.",
        },
        CategoryInfo {
            name: "patterns",
            display: "Patterns & Vertices",
            description: "Create compound patterns and inspect vertices.",
        },
        CategoryInfo {
            name: "search",
            display: "Search",
            description: "Search for text or token patterns in the graph.",
        },
        CategoryInfo {
            name: "insert",
            display: "Insert",
            description: "Insert text or token sequences, building the hypergraph hierarchy.",
        },
        CategoryInfo {
            name: "read",
            display: "Read",
            description: "Read back text and tree structures from the graph.",
        },
        CategoryInfo {
            name: "debug",
            display: "Debug & Inspection",
            description: "Snapshots, statistics, validation, and visual display.",
        },
    ]
}

// ---------------------------------------------------------------------------
// Workflow templates
// ---------------------------------------------------------------------------

/// A single step in a workflow template.
#[derive(Debug, Serialize)]
struct WorkflowStep {
    step: usize,
    description: &'static str,
    command: serde_json::Value,
}

/// A complete workflow template.
#[derive(Debug, Serialize)]
struct WorkflowTemplate {
    name: &'static str,
    title: &'static str,
    description: &'static str,
    steps: Vec<WorkflowStep>,
    tips: Vec<&'static str>,
}

/// Summary of an available workflow.
#[derive(Debug, Serialize)]
struct WorkflowSummary {
    name: &'static str,
    title: &'static str,
    description: &'static str,
}

fn available_workflows() -> Vec<WorkflowSummary> {
    vec![
        WorkflowSummary {
            name: "basic",
            title: "Basic End-to-End",
            description: "Create a workspace, add atoms, insert text, search, read, and save. The recommended starting workflow.",
        },
        WorkflowSummary {
            name: "bulk_insert",
            title: "Bulk Text Insertion",
            description: "Efficiently insert many text strings into a workspace using insert_sequences.",
        },
        WorkflowSummary {
            name: "search_and_read",
            title: "Search & Read",
            description: "Search for text in an existing workspace and read back the results.",
        },
        WorkflowSummary {
            name: "inspect",
            title: "Graph Inspection",
            description: "Debug and inspect graph state: statistics, validation, vertex details.",
        },
        WorkflowSummary {
            name: "persistence",
            title: "Save & Reopen",
            description: "Save a workspace to disk, close it, and reopen it later.",
        },
    ]
}

fn build_workflow(
    name: &str,
    ws: &str,
) -> Option<WorkflowTemplate> {
    let ws_val = serde_json::Value::String(ws.to_string());

    match name {
        "basic" => Some(WorkflowTemplate {
            name: "basic",
            title: "Basic End-to-End Workflow",
            description: "The standard workflow: create a workspace, populate it with atoms and text, search, read results, and save.",
            steps: vec![
                WorkflowStep {
                    step: 1,
                    description: "Create a new workspace",
                    command: serde_json::json!({
                        "command": "create_workspace",
                        "name": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 2,
                    description: "Add atoms for all unique characters your text will use",
                    command: serde_json::json!({
                        "command": "add_atoms",
                        "workspace": ws_val,
                        "chars": ["h", "e", "l", "o", " ", "w", "r", "d"],
                    }),
                },
                WorkflowStep {
                    step: 3,
                    description: "Insert text sequences — this builds the hypergraph hierarchy",
                    command: serde_json::json!({
                        "command": "insert_sequence",
                        "workspace": ws_val,
                        "text": "hello world",
                    }),
                },
                WorkflowStep {
                    step: 4,
                    description: "Search for a substring to find its token",
                    command: serde_json::json!({
                        "command": "search_sequence",
                        "workspace": ws_val,
                        "text": "hello",
                    }),
                },
                WorkflowStep {
                    step: 5,
                    description: "Read back text from a token index (use the index from search/insert results)",
                    command: serde_json::json!({
                        "command": "read_as_text",
                        "workspace": ws_val,
                        "index": 5,
                    }),
                },
                WorkflowStep {
                    step: 6,
                    description: "Check graph statistics",
                    command: serde_json::json!({
                        "command": "get_statistics",
                        "workspace": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 7,
                    description: "Save the workspace to disk before ending",
                    command: serde_json::json!({
                        "command": "save_workspace",
                        "name": ws_val,
                    }),
                },
            ],
            tips: vec![
                "Always add_atoms BEFORE insert_sequence — insertion requires atoms to exist.",
                "The index returned by insert_sequence can be used with read_as_text.",
                "insert_sequence returns already_existed=true if the text was already in the graph.",
                "Always save_workspace before ending your session.",
            ],
        }),

        "bulk_insert" => Some(WorkflowTemplate {
            name: "bulk_insert",
            title: "Bulk Text Insertion",
            description: "Insert many text strings efficiently. Use insert_sequences for batch operations.",
            steps: vec![
                WorkflowStep {
                    step: 1,
                    description: "Create or open a workspace",
                    command: serde_json::json!({
                        "command": "create_workspace",
                        "name": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 2,
                    description: "Add atoms for ALL unique characters across all texts",
                    command: serde_json::json!({
                        "command": "add_atoms",
                        "workspace": ws_val,
                        "chars": ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"," "],
                    }),
                },
                WorkflowStep {
                    step: 3,
                    description: "Batch-insert multiple sequences at once",
                    command: serde_json::json!({
                        "command": "insert_sequences",
                        "workspace": ws_val,
                        "texts": ["hello world", "hello there", "world peace"],
                    }),
                },
                WorkflowStep {
                    step: 4,
                    description: "Verify with statistics",
                    command: serde_json::json!({
                        "command": "get_statistics",
                        "workspace": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 5,
                    description: "Save",
                    command: serde_json::json!({
                        "command": "save_workspace",
                        "name": ws_val,
                    }),
                },
            ],
            tips: vec![
                "insert_sequences is more efficient than calling insert_sequence in a loop.",
                "Collect ALL unique characters across all texts before calling add_atoms.",
                "The texts parameter is a set — duplicates are automatically ignored.",
            ],
        }),

        "search_and_read" => Some(WorkflowTemplate {
            name: "search_and_read",
            title: "Search & Read Workflow",
            description: "Search for text patterns in an existing workspace, then read the results.",
            steps: vec![
                WorkflowStep {
                    step: 1,
                    description: "Open an existing workspace (skip if already open)",
                    command: serde_json::json!({
                        "command": "open_workspace",
                        "name": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 2,
                    description: "Search for text — check if complete=true in the result",
                    command: serde_json::json!({
                        "command": "search_sequence",
                        "workspace": ws_val,
                        "text": "hello",
                    }),
                },
                WorkflowStep {
                    step: 3,
                    description: "If search found a token, read it as text to confirm",
                    command: serde_json::json!({
                        "command": "read_as_text",
                        "workspace": ws_val,
                        "index": "<use token.index from search result>",
                    }),
                },
                WorkflowStep {
                    step: 4,
                    description: "Read the full tree structure for deeper inspection",
                    command: serde_json::json!({
                        "command": "read_pattern",
                        "workspace": ws_val,
                        "index": "<use token.index from search result>",
                    }),
                },
            ],
            tips: vec![
                "SearchResult.complete=true means the full text exists as one token.",
                "SearchResult.partial contains prefix/postfix matches when complete=false.",
                "SearchResult.query_exhausted=true means all query characters were consumed (text may be a prefix of a larger token).",
                "The token.index in the SearchResult is what you pass to read_as_text and read_pattern.",
            ],
        }),

        "inspect" => Some(WorkflowTemplate {
            name: "inspect",
            title: "Graph Inspection Workflow",
            description: "Debug and understand the current state of a workspace's graph.",
            steps: vec![
                WorkflowStep {
                    step: 1,
                    description: "Check statistics first (lightweight)",
                    command: serde_json::json!({
                        "command": "get_statistics",
                        "workspace": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 2,
                    description: "Validate graph integrity",
                    command: serde_json::json!({
                        "command": "validate_graph",
                        "workspace": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 3,
                    description: "Show the full graph (small graphs only)",
                    command: serde_json::json!({
                        "command": "show_graph",
                        "workspace": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 4,
                    description: "Inspect a specific vertex",
                    command: serde_json::json!({
                        "command": "show_vertex",
                        "workspace": ws_val,
                        "index": 0,
                    }),
                },
                WorkflowStep {
                    step: 5,
                    description: "Get detailed vertex info",
                    command: serde_json::json!({
                        "command": "get_vertex",
                        "workspace": ws_val,
                        "index": 0,
                    }),
                },
            ],
            tips: vec![
                "Always start with get_statistics to know the graph size.",
                "show_graph can produce very large output — avoid on graphs with >100 vertices.",
                "validate_graph checks structural integrity; an empty issues array means healthy.",
                "show_vertex is more focused than show_graph — use it for specific vertices.",
            ],
        }),

        "persistence" => Some(WorkflowTemplate {
            name: "persistence",
            title: "Save & Reopen Workflow",
            description: "Save workspace state to disk, close it, and reopen later.",
            steps: vec![
                WorkflowStep {
                    step: 1,
                    description: "Save the workspace to disk",
                    command: serde_json::json!({
                        "command": "save_workspace",
                        "name": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 2,
                    description: "Close the workspace (frees memory)",
                    command: serde_json::json!({
                        "command": "close_workspace",
                        "name": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 3,
                    description: "Later: reopen the workspace from disk",
                    command: serde_json::json!({
                        "command": "open_workspace",
                        "name": ws_val,
                    }),
                },
                WorkflowStep {
                    step: 4,
                    description: "Verify it loaded correctly",
                    command: serde_json::json!({
                        "command": "get_statistics",
                        "workspace": ws_val,
                    }),
                },
            ],
            tips: vec![
                "ALWAYS save before close — close does NOT auto-save!",
                "Workspaces are saved to <base_dir>/.context-engine/<name>/.",
                "list_workspaces only shows in-memory workspaces; saved-but-closed ones won't appear.",
                "After open_workspace, the graph is fully in memory and ready for operations.",
            ],
        }),

        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Tool implementations
// ---------------------------------------------------------------------------

#[tool_router]
impl ContextServer {
    /// Execute a context-engine command against a hypergraph workspace.
    ///
    /// This is the single entry point for all operations: workspace lifecycle,
    /// atom/pattern creation, search, insert, read, and debug commands.
    ///
    /// ## Workflow Example
    ///
    /// 1. Create a workspace: `{"command": "create_workspace", "name": "demo"}`
    /// 2. Add atoms: `{"command": "add_atoms", "workspace": "demo", "chars": ["a","b","c","d","e"]}`
    /// 3. Insert a sequence: `{"command": "insert_sequence", "workspace": "demo", "text": "abcde"}`
    /// 4. Search: `{"command": "search_sequence", "workspace": "demo", "text": "abc"}`
    /// 5. Read: `{"command": "read_as_text", "workspace": "demo", "index": 5}`
    /// 6. Save: `{"command": "save_workspace", "name": "demo"}`
    ///
    /// ## Available Commands
    ///
    /// **Workspace:** create_workspace, open_workspace, close_workspace,
    /// save_workspace, list_workspaces, delete_workspace
    ///
    /// **Atoms:** add_atom, add_atoms, get_atom, list_atoms
    ///
    /// **Patterns:** add_simple_pattern, get_vertex, list_vertices
    ///
    /// **Search:** search_pattern, search_sequence
    ///
    /// **Insert:** insert_first_match, insert_sequence, insert_sequences
    ///
    /// **Read:** read_pattern, read_as_text
    ///
    /// **Debug:** get_snapshot, get_statistics, validate_graph, show_graph, show_vertex
    #[tool(
        name = "execute",
        description = "Execute a context-engine hypergraph command. Send any Command JSON object and receive the corresponding CommandResult. Call the 'help' tool first to discover available commands, or the 'workflow' tool for ready-to-use command sequences."
    )]
    async fn execute_command(
        &self,
        Parameters(input): Parameters<ExecuteInput>,
    ) -> Result<CallToolResult, McpError> {
        tracing::debug!(command = ?input.command, "Executing command");

        let result = {
            let mut manager = self.manager.lock().map_err(|e| {
                McpError::internal_error(format!("Lock poisoned: {e}"), None)
            })?;
            execute(&mut manager, input.command)
        };

        match result {
            Ok(cmd_result) => {
                let output = ExecuteOutput {
                    success: true,
                    result: Some(cmd_result),
                    error: None,
                };
                let json =
                    serde_json::to_string_pretty(&output).map_err(|e| {
                        McpError::internal_error(
                            format!("Serialization failed: {e}"),
                            None,
                        )
                    })?;
                Ok(CallToolResult::success(vec![Content::text(json)]))
            },
            Err(api_error) => {
                tracing::warn!(error = %api_error, "Command failed");
                let output = ExecuteOutput {
                    success: false,
                    result: None,
                    error: Some(format!("{api_error}")),
                };
                let json =
                    serde_json::to_string_pretty(&output).map_err(|e| {
                        McpError::internal_error(
                            format!("Serialization failed: {e}"),
                            None,
                        )
                    })?;
                // Return as a successful MCP response with an error payload
                // so the agent can read and react to the error message.
                Ok(CallToolResult::success(vec![Content::text(json)]))
            },
        }
    }

    /// Get help about available commands.
    ///
    /// Call with no arguments for an overview, or specify a command name or
    /// category for detailed information.
    #[tool(
        name = "help",
        description = "Discover available context-engine commands. Call with no arguments for an overview of all commands grouped by category. Set 'command' to get detailed help for one command (parameters, example, result type, notes). Set 'category' to list only commands in that group (workspace, atoms, patterns, search, insert, read, debug)."
    )]
    async fn help_command(
        &self,
        Parameters(input): Parameters<HelpInput>,
    ) -> Result<CallToolResult, McpError> {
        let commands = all_commands();

        // Case 1: Specific command requested
        if let Some(ref cmd_name) = input.command {
            let needle = cmd_name.to_lowercase();
            if let Some(cmd) = commands.iter().find(|c| c.name == needle) {
                let json = serde_json::to_string_pretty(cmd).map_err(|e| {
                    McpError::internal_error(
                        format!("Serialization failed: {e}"),
                        None,
                    )
                })?;
                return Ok(CallToolResult::success(vec![Content::text(json)]));
            } else {
                // Fuzzy: show commands that contain the search term
                let matches: Vec<&str> = commands
                    .iter()
                    .filter(|c| {
                        c.name.contains(&needle)
                            || c.summary.to_lowercase().contains(&needle)
                    })
                    .map(|c| c.name)
                    .collect();

                let msg = if matches.is_empty() {
                    format!(
                        "No command named '{}'. Use help with no arguments to see all commands.",
                        cmd_name,
                    )
                } else {
                    format!(
                        "No exact match for '{}'. Did you mean one of: {}?\n\nCall help with the exact command name for details.",
                        cmd_name,
                        matches.join(", "),
                    )
                };
                return Ok(CallToolResult::success(vec![Content::text(msg)]));
            }
        }

        // Case 2: Specific category requested
        if let Some(ref cat_name) = input.category {
            let needle = cat_name.to_lowercase();
            let categories = all_categories();
            let cat = categories.iter().find(|c| c.name == needle);

            if cat.is_none() {
                let valid: Vec<&str> =
                    categories.iter().map(|c| c.name).collect();
                return Ok(CallToolResult::success(vec![Content::text(
                    format!(
                        "Unknown category '{}'. Valid categories: {}",
                        cat_name,
                        valid.join(", "),
                    ),
                )]));
            }
            let cat = cat.unwrap();

            let cat_commands: Vec<&CommandHelp> =
                commands.iter().filter(|c| c.category == needle).collect();

            let mut text = format!(
                "## {} ({})\n\n{}\n\n",
                cat.display, cat.name, cat.description
            );
            for cmd in &cat_commands {
                text.push_str(&format!(
                    "### {}\n{}\n\nExample:\n```\n{}\n```\n\nResult: {}\n\n",
                    cmd.name, cmd.summary, cmd.example, cmd.result_type
                ));
                if !cmd.parameters.is_empty() {
                    text.push_str("Parameters:\n");
                    for p in cmd.parameters {
                        text.push_str(&format!(
                            "  - `{}` ({}{}): {}\n",
                            p.name,
                            p.param_type,
                            if p.required {
                                ", required"
                            } else {
                                ", optional"
                            },
                            p.description,
                        ));
                    }
                    text.push('\n');
                }
                if !cmd.notes.is_empty() {
                    text.push_str(&format!("Note: {}\n\n", cmd.notes));
                }
                text.push_str("---\n\n");
            }

            return Ok(CallToolResult::success(vec![Content::text(text)]));
        }

        // Case 3: Full overview
        let categories = all_categories();
        let mut text = String::from(
            "# Context Engine — Command Reference\n\n\
             Use the `execute` tool to run any command. Use `help` with a specific\n\
             command name for detailed parameters and examples.\n\n\
             **Typical workflow:** create_workspace → add_atoms → insert_sequence → search_sequence → read_as_text → save_workspace\n\n\
             **Tip:** Use the `workflow` tool for ready-to-use command sequences.\n\n",
        );

        for cat in &categories {
            let cat_commands: Vec<&CommandHelp> =
                commands.iter().filter(|c| c.category == cat.name).collect();

            text.push_str(&format!(
                "## {} ({})\n\n{}\n\n",
                cat.display, cat.name, cat.description
            ));
            text.push_str("| Command | Summary |\n|---------|----------|\n");
            for cmd in &cat_commands {
                text.push_str(&format!(
                    "| `{}` | {} |\n",
                    cmd.name, cmd.summary
                ));
            }
            text.push('\n');
        }

        text.push_str(
            "---\n\n\
             Call `help` with `command: \"<name>\"` for full parameter details and examples.\n\
             Call `help` with `category: \"<name>\"` for all commands in a category.\n",
        );

        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    /// Get ready-to-use workflow templates.
    ///
    /// Returns named sequences of `execute` commands that agents can follow
    /// step-by-step.
    #[tool(
        name = "workflow",
        description = "Get ready-to-use command sequences for common tasks. Call with name='list' (or no arguments) to see available workflows. Set name to 'basic', 'bulk_insert', 'search_and_read', 'inspect', or 'persistence' to get a step-by-step template with example commands you can pass directly to the 'execute' tool. Set 'workspace' to customize the workspace name in the template (default: 'demo')."
    )]
    async fn workflow_command(
        &self,
        Parameters(input): Parameters<WorkflowInput>,
    ) -> Result<CallToolResult, McpError> {
        let name = input.name.to_lowercase();

        // List available workflows
        if name == "list" {
            let summaries = available_workflows();
            let mut text = String::from(
                "# Available Workflow Templates\n\n\
                 Call `workflow` with `name` set to one of these to get step-by-step commands:\n\n\
                 | Name | Description |\n\
                 |------|-------------|\n",
            );
            for s in &summaries {
                text.push_str(&format!(
                    "| `{}` | {} |\n",
                    s.name, s.description
                ));
            }
            text.push_str(&format!(
                "\nExample: call `workflow` with `name: \"basic\", workspace: \"my-graph\"` \
                 to get the basic workflow customized for your workspace name.\n"
            ));
            return Ok(CallToolResult::success(vec![Content::text(text)]));
        }

        // Build the requested workflow
        match build_workflow(&name, &input.workspace) {
            Some(wf) => {
                let json = serde_json::to_string_pretty(&wf).map_err(|e| {
                    McpError::internal_error(
                        format!("Serialization failed: {e}"),
                        None,
                    )
                })?;
                Ok(CallToolResult::success(vec![Content::text(json)]))
            },
            None => {
                let available: Vec<&str> =
                    available_workflows().iter().map(|s| s.name).collect();
                Ok(CallToolResult::success(vec![Content::text(format!(
                    "Unknown workflow '{}'. Available workflows: {}\n\nCall workflow with name='list' to see descriptions.",
                    name,
                    available.join(", "),
                ))]))
            },
        }
    }
}

// ---------------------------------------------------------------------------
// ServerHandler (MCP metadata)
// ---------------------------------------------------------------------------

#[tool_handler]
impl ServerHandler for ContextServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            instructions: Some(
                "Context Engine MCP Server — manages hypergraph workspaces.\n\n\
                 **Start here:** Call the `help` tool to discover available commands,\n\
                 or the `workflow` tool for ready-to-use command sequences.\n\n\
                 Then use the `execute` tool with a command JSON object.\n\n\
                 Quick start:\n\
                 1. Call `workflow` with name=\"basic\" to get a step-by-step template\n\
                 2. Follow the steps using the `execute` tool\n\
                 3. Call `help` with command=\"<name>\" for detailed parameter info\n\n\
                 Or dive straight in:\n\
                 1. {\"command\": \"create_workspace\", \"name\": \"demo\"}\n\
                 2. {\"command\": \"add_atoms\", \"workspace\": \"demo\", \"chars\": [\"a\",\"b\",\"c\"]}\n\
                 3. {\"command\": \"insert_sequence\", \"workspace\": \"demo\", \"text\": \"abc\"}\n\
                 4. {\"command\": \"search_sequence\", \"workspace\": \"demo\", \"text\": \"ab\"}\n\
                 5. {\"command\": \"save_workspace\", \"name\": \"demo\"}"
                    .to_string(),
            ),
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            ..Default::default()
        }
    }
}

// ---------------------------------------------------------------------------
// Server launcher
// ---------------------------------------------------------------------------

/// Run the MCP server on stdio transport.
///
/// This blocks until the MCP client disconnects (stdin EOF).
pub async fn run_mcp_server(
    base_dir: PathBuf
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let server = ContextServer::new(base_dir);

    tracing::info!("Starting context-mcp server on stdio");

    let service = server.serve(stdio()).await.inspect_err(|e| {
        eprintln!("Server error: {:?}", e);
    })?;

    service.waiting().await?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use context_api::commands::Command;
    use rmcp::model::RawContent;

    /// Helper: create a server backed by a temporary directory.
    fn tmp_server() -> (tempfile::TempDir, ContextServer) {
        let tmp = tempfile::tempdir().expect("create temp dir");
        let server = ContextServer::new(tmp.path().to_path_buf());
        (tmp, server)
    }

    /// Parse the text content of a `CallToolResult` into an `ExecuteOutput`.
    fn parse_output(result: &CallToolResult) -> ExecuteOutput {
        let content =
            result.content.first().expect("result should have content");
        match &content.raw {
            RawContent::Text(text_content) =>
                serde_json::from_str(&text_content.text)
                    .expect("should parse as ExecuteOutput"),
            _ => panic!("Expected text content"),
        }
    }

    /// Extract raw text from a `CallToolResult`.
    fn extract_text(result: &CallToolResult) -> String {
        let content =
            result.content.first().expect("result should have content");
        match &content.raw {
            RawContent::Text(text_content) => text_content.text.clone(),
            _ => panic!("Expected text content"),
        }
    }

    /// Helper to execute a command via the server and return the parsed output.
    async fn exec(
        server: &ContextServer,
        command: Command,
    ) -> ExecuteOutput {
        let input = Parameters(ExecuteInput { command });
        let result = server
            .execute_command(input)
            .await
            .expect("MCP call should not fail");
        parse_output(&result)
    }

    // =======================================================================
    // Execute tool tests
    // =======================================================================

    #[tokio::test]
    async fn test_create_workspace() {
        let (_tmp, server) = tmp_server();

        let output = exec(
            &server,
            Command::CreateWorkspace {
                name: "test".into(),
            },
        )
        .await;

        assert!(output.success, "create_workspace should succeed");
        assert!(output.result.is_some());
        assert!(output.error.is_none());
    }

    #[tokio::test]
    async fn test_error_workspace_not_found() {
        let (_tmp, server) = tmp_server();

        // Try to open a workspace that doesn't exist
        let output = exec(
            &server,
            Command::OpenWorkspace {
                name: "nope".into(),
            },
        )
        .await;

        assert!(!output.success, "open nonexistent should fail");
        assert!(output.result.is_none());
        assert!(output.error.is_some());
        assert!(
            output.error.as_ref().unwrap().contains("not found"),
            "error should mention 'not found': {:?}",
            output.error
        );
    }

    #[tokio::test]
    async fn test_add_atoms_and_list() {
        let (_tmp, server) = tmp_server();

        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;

        let output = exec(
            &server,
            Command::AddAtoms {
                workspace: "ws".into(),
                chars: vec!['a', 'b', 'c'],
            },
        )
        .await;
        assert!(output.success);

        // Verify via list_atoms
        let output = exec(
            &server,
            Command::ListAtoms {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success);

        match &output.result {
            Some(CommandResult::AtomInfoList { atoms }) => {
                assert_eq!(atoms.len(), 3, "should have 3 atoms");
            },
            other => panic!("Expected AtomInfoList, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_insert_and_search_workflow() {
        let (_tmp, server) = tmp_server();

        // Create + atoms + insert
        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;
        exec(
            &server,
            Command::AddAtoms {
                workspace: "ws".into(),
                chars: vec!['a', 'b', 'c', 'd', 'e'],
            },
        )
        .await;

        let insert_out = exec(
            &server,
            Command::InsertSequence {
                workspace: "ws".into(),
                text: "abcde".into(),
            },
        )
        .await;
        assert!(insert_out.success);

        // Search for prefix
        let search_out = exec(
            &server,
            Command::SearchSequence {
                workspace: "ws".into(),
                text: "abc".into(),
            },
        )
        .await;
        assert!(search_out.success);

        // Full match
        let search_full = exec(
            &server,
            Command::SearchSequence {
                workspace: "ws".into(),
                text: "abcde".into(),
            },
        )
        .await;
        assert!(search_full.success);
    }

    #[tokio::test]
    async fn test_statistics() {
        let (_tmp, server) = tmp_server();

        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;
        exec(
            &server,
            Command::AddAtoms {
                workspace: "ws".into(),
                chars: vec!['x', 'y'],
            },
        )
        .await;

        let output = exec(
            &server,
            Command::GetStatistics {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success);

        match &output.result {
            Some(CommandResult::Statistics(stats)) => {
                assert_eq!(stats.atom_count, 2);
                assert!(stats.vertex_count >= 2);
            },
            other => panic!("Expected Statistics, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_save_close_reopen_persistence() {
        let (_tmp, server) = tmp_server();

        // Create, populate, save, close
        exec(
            &server,
            Command::CreateWorkspace {
                name: "persist".into(),
            },
        )
        .await;
        exec(
            &server,
            Command::AddAtoms {
                workspace: "persist".into(),
                chars: vec!['p', 'q', 'r'],
            },
        )
        .await;
        exec(
            &server,
            Command::InsertSequence {
                workspace: "persist".into(),
                text: "pqr".into(),
            },
        )
        .await;

        // Save
        let save_out = exec(
            &server,
            Command::SaveWorkspace {
                name: "persist".into(),
            },
        )
        .await;
        assert!(save_out.success, "save should succeed");

        // Close
        let close_out = exec(
            &server,
            Command::CloseWorkspace {
                name: "persist".into(),
            },
        )
        .await;
        assert!(close_out.success);

        // Reopen
        let open_out = exec(
            &server,
            Command::OpenWorkspace {
                name: "persist".into(),
            },
        )
        .await;
        assert!(open_out.success);

        // Verify contents survived
        let stats_out = exec(
            &server,
            Command::GetStatistics {
                workspace: "persist".into(),
            },
        )
        .await;
        assert!(stats_out.success);
        match &stats_out.result {
            Some(CommandResult::Statistics(stats)) => {
                assert!(
                    stats.atom_count >= 3,
                    "should still have at least 3 atoms"
                );
            },
            other => panic!("Expected Statistics, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_list_workspaces() {
        let (_tmp, server) = tmp_server();

        // Initially empty
        let out = exec(&server, Command::ListWorkspaces).await;
        assert!(out.success);
        match &out.result {
            Some(CommandResult::WorkspaceInfoList { workspaces }) => {
                assert!(workspaces.is_empty());
            },
            other => panic!("Expected WorkspaceInfoList, got {other:?}"),
        }

        // Create one
        exec(&server, Command::CreateWorkspace { name: "a".into() }).await;

        let out = exec(&server, Command::ListWorkspaces).await;
        assert!(out.success);
        match &out.result {
            Some(CommandResult::WorkspaceInfoList { workspaces }) => {
                assert_eq!(workspaces.len(), 1);
            },
            other => panic!("Expected WorkspaceInfoList, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_execute_input_serde_flatten() {
        // Verify that ExecuteInput with serde(flatten) deserializes correctly
        let json = r#"{"command": "create_workspace", "name": "demo"}"#;
        let input: ExecuteInput =
            serde_json::from_str(json).expect("should deserialize");
        match input.command {
            Command::CreateWorkspace { name } => {
                assert_eq!(name, "demo");
            },
            other => panic!("Expected CreateWorkspace, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_execute_input_serde_complex() {
        let json = r#"{"command": "insert_sequence", "workspace": "ws", "text": "hello world"}"#;
        let input: ExecuteInput =
            serde_json::from_str(json).expect("should deserialize");
        match input.command {
            Command::InsertSequence { workspace, text } => {
                assert_eq!(workspace, "ws");
                assert_eq!(text, "hello world");
            },
            other => panic!("Expected InsertSequence, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_validate_graph() {
        let (_tmp, server) = tmp_server();

        exec(&server, Command::CreateWorkspace { name: "ws".into() }).await;

        let output = exec(
            &server,
            Command::ValidateGraph {
                workspace: "ws".into(),
            },
        )
        .await;
        assert!(output.success);

        match &output.result {
            Some(CommandResult::ValidationReport(report)) => {
                assert!(report.valid, "empty graph should be valid");
            },
            other => panic!("Expected ValidationReport, got {other:?}"),
        }
    }

    // =======================================================================
    // Help tool tests
    // =======================================================================

    #[tokio::test]
    async fn test_help_overview() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(HelpInput {
            command: None,
            category: None,
        });
        let result = server
            .help_command(input)
            .await
            .expect("help should not fail");
        let text = extract_text(&result);

        // Should contain all categories
        assert!(
            text.contains("Workspace Lifecycle"),
            "should have workspace category"
        );
        assert!(text.contains("Atoms"), "should have atoms category");
        assert!(text.contains("Search"), "should have search category");
        assert!(text.contains("Insert"), "should have insert category");
        assert!(text.contains("Read"), "should have read category");
        assert!(text.contains("Debug"), "should have debug category");

        // Should mention key commands
        assert!(text.contains("create_workspace"));
        assert!(text.contains("insert_sequence"));
        assert!(text.contains("search_sequence"));
    }

    #[tokio::test]
    async fn test_help_specific_command() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(HelpInput {
            command: Some("insert_sequence".to_string()),
            category: None,
        });
        let result = server
            .help_command(input)
            .await
            .expect("help should not fail");
        let text = extract_text(&result);

        // Should parse as JSON with command details
        let parsed: serde_json::Value = serde_json::from_str(&text)
            .expect("help output should be valid JSON");
        assert_eq!(parsed["name"], "insert_sequence");
        assert_eq!(parsed["category"], "insert");
        assert!(parsed["summary"].as_str().unwrap().len() > 0);
        assert!(
            parsed["example"]
                .as_str()
                .unwrap()
                .contains("insert_sequence")
        );
        assert!(parsed["parameters"].as_array().unwrap().len() > 0);
    }

    #[tokio::test]
    async fn test_help_unknown_command_fuzzy() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(HelpInput {
            command: Some("insert".to_string()),
            category: None,
        });
        let result = server
            .help_command(input)
            .await
            .expect("help should not fail");
        let text = extract_text(&result);

        // Should suggest similar commands
        assert!(
            text.contains("insert_sequence")
                || text.contains("insert_first_match"),
            "should suggest commands containing 'insert': {text}"
        );
    }

    #[tokio::test]
    async fn test_help_category() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(HelpInput {
            command: None,
            category: Some("search".to_string()),
        });
        let result = server
            .help_command(input)
            .await
            .expect("help should not fail");
        let text = extract_text(&result);

        assert!(
            text.contains("search_pattern"),
            "should list search_pattern"
        );
        assert!(
            text.contains("search_sequence"),
            "should list search_sequence"
        );
        // Should NOT contain commands from other categories as section headers
        assert!(
            !text.contains("### create_workspace"),
            "should not have workspace commands"
        );
    }

    #[tokio::test]
    async fn test_help_invalid_category() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(HelpInput {
            command: None,
            category: Some("nonexistent".to_string()),
        });
        let result = server
            .help_command(input)
            .await
            .expect("help should not fail");
        let text = extract_text(&result);

        assert!(
            text.contains("Unknown category"),
            "should report unknown category: {text}"
        );
        assert!(text.contains("workspace"), "should list valid categories");
    }

    #[tokio::test]
    async fn test_help_all_commands_covered() {
        // Verify all Command enum variants have a help entry
        let commands = all_commands();
        let names: Vec<&str> = commands.iter().map(|c| c.name).collect();

        let expected = [
            "create_workspace",
            "open_workspace",
            "close_workspace",
            "save_workspace",
            "list_workspaces",
            "delete_workspace",
            "add_atom",
            "add_atoms",
            "get_atom",
            "list_atoms",
            "add_simple_pattern",
            "get_vertex",
            "list_vertices",
            "search_pattern",
            "search_sequence",
            "insert_first_match",
            "insert_sequence",
            "insert_sequences",
            "read_pattern",
            "read_as_text",
            "get_snapshot",
            "get_statistics",
            "validate_graph",
            "show_graph",
            "show_vertex",
        ];

        for exp in &expected {
            assert!(
                names.contains(exp),
                "Missing help entry for command: {}",
                exp,
            );
        }
    }

    // =======================================================================
    // Workflow tool tests
    // =======================================================================

    #[tokio::test]
    async fn test_workflow_list() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(WorkflowInput {
            name: "list".to_string(),
            workspace: "demo".to_string(),
        });
        let result = server
            .workflow_command(input)
            .await
            .expect("workflow should not fail");
        let text = extract_text(&result);

        assert!(text.contains("basic"), "should list basic workflow");
        assert!(
            text.contains("bulk_insert"),
            "should list bulk_insert workflow"
        );
        assert!(
            text.contains("search_and_read"),
            "should list search_and_read"
        );
        assert!(text.contains("inspect"), "should list inspect");
        assert!(text.contains("persistence"), "should list persistence");
    }

    #[tokio::test]
    async fn test_workflow_basic() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(WorkflowInput {
            name: "basic".to_string(),
            workspace: "my-graph".to_string(),
        });
        let result = server
            .workflow_command(input)
            .await
            .expect("workflow should not fail");
        let text = extract_text(&result);

        // Should be valid JSON
        let parsed: serde_json::Value = serde_json::from_str(&text)
            .expect("workflow output should be JSON");

        assert_eq!(parsed["name"], "basic");
        assert!(
            parsed["steps"].as_array().unwrap().len() >= 5,
            "basic workflow should have at least 5 steps"
        );
        assert!(
            parsed["tips"].as_array().unwrap().len() > 0,
            "should have tips"
        );

        // Verify workspace name substitution
        let json_text = text;
        assert!(
            json_text.contains("my-graph"),
            "should contain customized workspace name"
        );
    }

    #[tokio::test]
    async fn test_workflow_default_workspace() {
        let (_tmp, server) = tmp_server();

        // Test default values
        let input = Parameters(WorkflowInput {
            name: "basic".to_string(),
            workspace: "demo".to_string(),
        });
        let result = server
            .workflow_command(input)
            .await
            .expect("workflow should not fail");
        let text = extract_text(&result);

        assert!(text.contains("demo"), "default workspace should be 'demo'");
    }

    #[tokio::test]
    async fn test_workflow_unknown() {
        let (_tmp, server) = tmp_server();

        let input = Parameters(WorkflowInput {
            name: "nonexistent".to_string(),
            workspace: "demo".to_string(),
        });
        let result = server
            .workflow_command(input)
            .await
            .expect("workflow should not fail");
        let text = extract_text(&result);

        assert!(
            text.contains("Unknown workflow"),
            "should report unknown: {text}"
        );
        assert!(text.contains("basic"), "should suggest available workflows");
    }

    #[tokio::test]
    async fn test_workflow_all_templates_build() {
        // Verify all advertised workflows can actually be built
        let summaries = available_workflows();
        for s in &summaries {
            let wf = build_workflow(s.name, "test-ws");
            assert!(
                wf.is_some(),
                "Workflow '{}' is advertised but build_workflow returns None",
                s.name,
            );
            let wf = wf.unwrap();
            assert!(!wf.steps.is_empty(), "Workflow '{}' has no steps", s.name);
            assert!(!wf.tips.is_empty(), "Workflow '{}' has no tips", s.name);

            // Verify it serializes to valid JSON
            let json = serde_json::to_string_pretty(&wf);
            assert!(
                json.is_ok(),
                "Workflow '{}' failed to serialize: {:?}",
                s.name,
                json.err()
            );
        }
    }

    #[tokio::test]
    async fn test_workflow_steps_have_valid_commands() {
        // Verify basic workflow steps contain valid command names
        let wf = build_workflow("basic", "demo").unwrap();
        for step in &wf.steps {
            let cmd = step.command.get("command");
            assert!(
                cmd.is_some(),
                "Step {} should have a 'command' field",
                step.step,
            );
            let cmd_name = cmd.unwrap().as_str().unwrap();
            let known: Vec<&str> =
                all_commands().iter().map(|c| c.name).collect();
            assert!(
                known.contains(&cmd_name),
                "Step {} references unknown command '{}' (known: {:?})",
                step.step,
                cmd_name,
                known,
            );
        }
    }
}
