id = "72b641b1-6620-4043-b956-102d826ce8ea"
created_at = "2026-08-25T13:35:25.594296300+00:00"
title = "Meta-workspace workflow-tools consumer topology"
state = "approved"
component = "workflow-tools"
related_tickets = "389f90d9-fb06-49b7-948b-0dbd14dcfeca"
scope = "public"
slug = "workflow-tools/meta-workspace-consumers"
type = "specification"
