id = "21893f5f-e57f-4cdf-b5de-39f42ae5d89d"
created_at = "2026-07-25T13:56:52.302565600+00:00"
title = "[workflow-tools][per-tool] Extract rule tool as a single `rule` domain crate (api + transport bins)"
state = "open"
component = "rule"
depends_on = ["0da6894c-dcbb-4196-8ac7-b6fae7c40ec9", "1c452ff1-6edc-47c8-a73d-d07ce9b4d473", "dbe0e955-c1b4-414d-820c-10c3fbbb5d3d"]
effort = "1200"
priority = "high"
risk_level = "medium"
type = "task"
