id = "47a0bcc3-f42d-475e-b05a-777293c4698e"
created_at = "2026-07-25T13:55:30.448597600+00:00"
title = "[workflow-tools][artifacts] Establish repo-level and per-tool self-referential artifact stores"
state = "open"
component = "workflow-tools"
depends_on = ["b525a7fa-f59d-4a14-b234-2ec7b8a42e95"]
effort = "900"
priority = "high"
risk_level = "medium"
type = "task"
