id = "dda04f91-3e03-46bb-a553-d9a172139027"
created_at = "2026-07-04T03:30:31.103498400+00:00"
title = "[ticket-api][watcher] Add reconcile lifecycle tracing"
state = "in-implementation"
type = "tracker-improvement"
